package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Executor - Descr: Frequency for healtchecking garden Default: 10m
*/
	Executor *Executor `yaml:"executor,omitempty"`

	/*Rep - Descr: Address to the BBS Server Default: bbs.service.cf.internal:8889
*/
	Rep *Rep `yaml:"rep,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}