package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Rep struct {

	/*Diego - Descr: Address to the BBS Server Default: bbs.service.cf.internal:8889
*/
	Diego *Diego `yaml:"diego,omitempty"`

	/*RootfsProviders - Descr: Array of schemes for which the underlying garden can support arbitrary root filesystems Default: [docker]
*/
	RootfsProviders interface{} `yaml:"rootfs_providers,omitempty"`

	/*TrustedCerts - Descr: Concatenation of trusted CA certificates to be made available inside the rootfses Default: <nil>
*/
	TrustedCerts interface{} `yaml:"trusted_certs,omitempty"`

	/*DropsondePort - Descr: local metron agent's port Default: 3457
*/
	DropsondePort interface{} `yaml:"dropsonde_port,omitempty"`

	/*Bbs - Descr: Address to the BBS Server Default: bbs.service.cf.internal:8889
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

	/*Stack - Descr: The stack for which to handle requests Default: cflinuxfs2
*/
	Stack interface{} `yaml:"stack,omitempty"`

	/*EvacuationTimeoutInSeconds - Descr: The time to wait for evacuation to complete in seconds Default: 600
*/
	EvacuationTimeoutInSeconds interface{} `yaml:"evacuation_timeout_in_seconds,omitempty"`

	/*EvacuationPollingIntervalInSeconds - Descr: The interval to look for completed tasks and LRPs during evacuation in seconds Default: 10
*/
	EvacuationPollingIntervalInSeconds interface{} `yaml:"evacuation_polling_interval_in_seconds,omitempty"`

	/*PreloadedRootfses - Descr: Array of name:absolute_path pairs representing root filesystems preloaded onto the underlying garden Default: [cflinuxfs2:/var/vcap/packages/rootfs_cflinuxfs2/rootfs]
*/
	PreloadedRootfses interface{} `yaml:"preloaded_rootfses,omitempty"`

	/*ListenAddr - Descr: address to serve auction and LRP stop requests on Default: 0.0.0.0:1800
*/
	ListenAddr interface{} `yaml:"listen_addr,omitempty"`

	/*DebugAddr - Descr: address at which to serve debug info Default: 0.0.0.0:17008
*/
	DebugAddr interface{} `yaml:"debug_addr,omitempty"`

	/*PollingIntervalInSeconds - Descr: The interval to look for completed tasks and LRPs in seconds Default: 30
*/
	PollingIntervalInSeconds interface{} `yaml:"polling_interval_in_seconds,omitempty"`

	/*LogLevel - Descr: Log level Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

	/*Zone - Descr: The zone associated with the rep Default: <nil>
*/
	Zone interface{} `yaml:"zone,omitempty"`

}