package cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*Mbus - Descr: Mbus URL used by deployed BOSH agents Default: 
*/
	Mbus interface{} `yaml:"mbus,omitempty"`

}