package cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Env struct {

	/*HttpsProxy - Descr: Https proxy to connect to cloud API's Default: <nil>
*/
	HttpsProxy interface{} `yaml:"https_proxy,omitempty"`

	/*NoProxy - Descr: No proxy environment variable Default: <nil>
*/
	NoProxy interface{} `yaml:"no_proxy,omitempty"`

	/*HttpProxy - Descr: Http proxy to connect to cloud API's Default: <nil>
*/
	HttpProxy interface{} `yaml:"http_proxy,omitempty"`

}