package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BootVolumeCloudProperties struct {

	/*Type - Descr: Volume type for the boot volume (optional) Default: <nil>
*/
	Type interface{} `yaml:"type,omitempty"`

}