package nats 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Http struct {

	/*User - Descr: Username clients must use to access nats mbus via HTTP connection (optional) Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Port - Descr: TCP port NATS listens on for HTTP connections (optional) Default: 9222
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Password - Descr: Password clients must use to access nats mbus via HTTP connection (optional) Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}