package nats 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nats struct {

	/*Http - Descr: Password clients must use to access nats mbus via HTTP connection (optional) Default: <nil>
*/
	Http *Http `yaml:"http,omitempty"`

	/*PingMaxOutstanding - Descr: Maximum number of pings before declaring a client unresponsive Default: 2
*/
	PingMaxOutstanding interface{} `yaml:"ping_max_outstanding,omitempty"`

	/*AuthTimeout - Descr: Timeout (in seconds) for clients to send auth credentials Default: 1
*/
	AuthTimeout interface{} `yaml:"auth_timeout,omitempty"`

	/*PingInterval - Descr: Time interval (in seconds) pings from server Default: 5
*/
	PingInterval interface{} `yaml:"ping_interval,omitempty"`

	/*Password - Descr: Password clients must use to access nats mbus Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Port - Descr: TCP port nats mbus listens on Default: 4222
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Nats - Descr: TCP port nats mbus listens on Default: 4222
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*NoEpoll - Descr: Disable epoll (Linux) Default: false
*/
	NoEpoll interface{} `yaml:"no_epoll,omitempty"`

	/*User - Descr: Username clients must use to access nats mbus Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*ListenAddress - Descr: IP address nats mbus listens on Default: 0.0.0.0
*/
	ListenAddress interface{} `yaml:"listen_address,omitempty"`

	/*NoKqueue - Descr: Disable kqueue (MacOSX and BSD) Default: true
*/
	NoKqueue interface{} `yaml:"no_kqueue,omitempty"`

}