package cf_redis_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*BackendPort - Descr: The port for the broker unicorn process to run on Default: 10005
*/
	BackendPort interface{} `yaml:"backend_port,omitempty"`

	/*Network - Descr: The name of the network that the redis broker runs on. Default: <nil>
*/
	Network interface{} `yaml:"network,omitempty"`

	/*DedicatedNodes - Descr: List of node IPs for the dedicated plan Default: []
*/
	DedicatedNodes interface{} `yaml:"dedicated_nodes,omitempty"`

	/*Name - Descr: Name of the broker, to be used in cf commandline operations and by the broker-registrar Default: redis
*/
	Name interface{} `yaml:"name,omitempty"`

	/*ProcessCheckInterval - Descr: Interval in seconds between checks for dead processes Default: 10
*/
	ProcessCheckInterval interface{} `yaml:"process_check_interval,omitempty"`

	/*DedicatedVmPlanId - Descr: Dedicated-VM plan id displayed in the catalog metadata Default: 74E8984C-5F8C-11E4-86BE-07807B3B2589
*/
	DedicatedVmPlanId interface{} `yaml:"dedicated_vm_plan_id,omitempty"`

	/*ServiceInstanceLimit - Descr: The maximum number of instances allowed Default: <nil>
*/
	ServiceInstanceLimit interface{} `yaml:"service_instance_limit,omitempty"`

	/*Backups - Descr: Temporary directory to use for backups. MUST be on same device (persistent disk) as redis data Default: /var/vcap/store/tmp_backup
*/
	Backups *Backups `yaml:"backups,omitempty"`

	/*DedicatedPort - Descr: The port used by the redis instances Default: 6379
*/
	DedicatedPort interface{} `yaml:"dedicated_port,omitempty"`

	/*BackendHost - Descr: The port for the broker unicorn process to run on Default: localhost
*/
	BackendHost interface{} `yaml:"backend_host,omitempty"`

	/*Subdomain - Descr: Subdomain for route registrar Default: redis-broker
*/
	Subdomain interface{} `yaml:"subdomain,omitempty"`

	/*StartRedisTimeout - Descr: Maximum wait time in seconds for Redis to start up Default: 600
*/
	StartRedisTimeout interface{} `yaml:"start_redis_timeout,omitempty"`

	/*Auth - Descr: The username for HTTP Basic Auth on the Broker, also used for the agent Default: admin
*/
	Auth *Auth `yaml:"auth,omitempty"`

	/*SharedVmPlanId - Descr: Shared-VM plan id displayed in the catalog metadata Default: C210CA06-E7E5-4F5D-A5AA-7A2C51CC290E
*/
	SharedVmPlanId interface{} `yaml:"shared_vm_plan_id,omitempty"`

	/*ServiceName - Descr: Service name displayed in the catalog metadata Default: p-redis
*/
	ServiceName interface{} `yaml:"service_name,omitempty"`

	/*ServiceId - Descr: Service id displayed in the catalog metadata Default: EEA47C3A-569C-4C24-869D-0ADB5B337A4C
*/
	ServiceId interface{} `yaml:"service_id,omitempty"`

}