package cf_redis_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Redis struct {

	/*Replication - Descr: Set TCP_NODELAY on the slave socket after SYNC. Default: no
*/
	Replication *Replication `yaml:"replication,omitempty"`

	/*TcpKeepAlive - Descr: TCP keepalive Default: 0
*/
	TcpKeepAlive interface{} `yaml:"tcp_keep_alive,omitempty"`

	/*DataDirectory - Descr: The directory which stores the persisted broker data Default: /var/vcap/store/cf-redis-broker/redis-data
*/
	DataDirectory interface{} `yaml:"data_directory,omitempty"`

	/*ClientTimeout - Descr: Close the connection after a client is idle for N seconds (0 to disable) Default: 0
*/
	ClientTimeout interface{} `yaml:"client_timeout,omitempty"`

	/*ConfPath - Descr: The shared conf file for all Redis instances Default: /var/vcap/jobs/cf-redis-broker/config/redis.conf
*/
	ConfPath interface{} `yaml:"conf_path,omitempty"`

	/*Broker - Descr: Temporary directory to use for backups. MUST be on same device (persistent disk) as redis data Default: /var/vcap/store/tmp_backup
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Snapshotting - Descr: save <seconds> <changes>; Will save the DB if both the given number of seconds and the given number of write operations against the DB occurred. Default: [900 1 300 10 60 10000]
*/
	Snapshotting *Snapshotting `yaml:"snapshotting,omitempty"`

	/*BgSaveCommand - Descr: The name of the obfuscated redis BGSAVE command. Default: 
*/
	BgSaveCommand interface{} `yaml:"bg_save_command,omitempty"`

	/*Databases - Descr: Set the number of databases. The default database is DB 0. Default: 16
*/
	Databases interface{} `yaml:"databases,omitempty"`

	/*LogDirectory - Descr: The directory which stores the redis server logs Default: /var/vcap/sys/log/redis
*/
	LogDirectory interface{} `yaml:"log_directory,omitempty"`

	/*SlowLog - Descr: the execution time, in microseconds, to exceed in order for the command to get logged Default: 10000
*/
	SlowLog *SlowLog `yaml:"slow_log,omitempty"`

	/*ConfigCommand - Descr: The name of the obfuscated redis CONFIG command. Default: <nil>
*/
	ConfigCommand interface{} `yaml:"config_command,omitempty"`

	/*Maxmemory - Descr: The maximum memory (in bytes) that Redis will use before evicting old data Default: 524288000
*/
	Maxmemory interface{} `yaml:"maxmemory,omitempty"`

	/*StatefilePath - Descr: Path to the broker statefile Default: /var/vcap/store/cf-redis-broker/statefile.json
*/
	StatefilePath interface{} `yaml:"statefile_path,omitempty"`

	/*LogLevel - Descr: Specify the server log verbosity level (debug, verbose, notice, warning) Default: notice
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

	/*LuaTimeLimit - Descr: Max execution time of a Lua script in milliseconds. Default: 5000
*/
	LuaTimeLimit interface{} `yaml:"lua_time_limit,omitempty"`

	/*SaveCommand - Descr: The name of the obfuscated redis SAVE command. Default: 
*/
	SaveCommand interface{} `yaml:"save_command,omitempty"`

}