package cf_redis_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Replication struct {

	/*SlaveServeStaleData - Descr: Master-Slave replication. Use slaveof to make a Redis instance a copy of another Redis server. Default: yes
*/
	SlaveServeStaleData interface{} `yaml:"slave_serve_stale_data,omitempty"`

	/*SlavePriority - Descr: The slave priority is an integer number published by Redis in the INFO output. It is used by Redis Sentinel in order to select a slave to promote into a master if the master is no longer working correctly. Default: 100
*/
	SlavePriority interface{} `yaml:"slave_priority,omitempty"`

	/*SlaveReadOnly - Descr: Configure a slave instance to accept writes or not. Default: yes
*/
	SlaveReadOnly interface{} `yaml:"slave_read_only,omitempty"`

	/*ReplDisableTcpNodelay - Descr: Set TCP_NODELAY on the slave socket after SYNC. Default: no
*/
	ReplDisableTcpNodelay interface{} `yaml:"repl_disable_tcp_nodelay,omitempty"`

}