package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Admin struct {

	/*ClientSecret - Descr: Secret of the admin client - a client named admin with uaa.admin as an authority Default: <nil>
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

}