package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AuthenticationPolicy struct {

	/*Global - Descr: Number of seconds to lock out an account when lockoutAfterFailures failures is exceeded Default: 300
*/
	Global *Global `yaml:"global,omitempty"`

	/*CountFailuresWithinSeconds - Descr: Number of seconds in which lockoutAfterFailures failures must occur in order for account to be locked Default: 3600
*/
	CountFailuresWithinSeconds interface{} `yaml:"countFailuresWithinSeconds,omitempty"`

	/*LockoutPeriodSeconds - Descr: Number of seconds to lock out an account when lockoutAfterFailures failures is exceeded Default: 300
*/
	LockoutPeriodSeconds interface{} `yaml:"lockoutPeriodSeconds,omitempty"`

	/*LockoutAfterFailures - Descr: Number of allowed failures before account is locked Default: 5
*/
	LockoutAfterFailures interface{} `yaml:"lockoutAfterFailures,omitempty"`

}