package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Authentication struct {

	/*Policy - Descr: Number of allowed failures before account is locked Default: 5
*/
	Policy *AuthenticationPolicy `yaml:"policy,omitempty"`

}