package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Client struct {

	/*Autoapprove - Descr: Deprecated Default: [login support-signon]
*/
	Autoapprove interface{} `yaml:"autoapprove,omitempty"`

}