package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Jwt struct {

	/*VerificationKey - Descr: The key used to verify JWT-based OAuth2 tokens Default: <nil>
*/
	VerificationKey interface{} `yaml:"verification_key,omitempty"`

	/*Claims - Descr: List of claims to exclude from the JWT-based OAuth2 tokens Default: <nil>
*/
	Claims *Claims `yaml:"claims,omitempty"`

	/*SigningKey - Descr: The key used to sign the JWT-based OAuth2 tokens Default: <nil>
*/
	SigningKey interface{} `yaml:"signing_key,omitempty"`

	/*Policy - Descr: Map of key ids to key pairs (signing and verification keys) Default: <nil>
*/
	Policy *JwtPolicy `yaml:"policy,omitempty"`

}