package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Logout struct {

	/*Redirect - Descr: A list of URLs. When this list is non null, including empty, and disable=false, logout redirects are allowed, but limited to the whitelist URLs. If a redirect parameter value is not white listed, redirect will be to the default URL. Default: <nil>
*/
	Redirect *Redirect `yaml:"redirect,omitempty"`

}