package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Policy struct {

	/*RequireSpecialCharacter - Descr: Minimum number of special characters required for password to be considered valid Default: 0
*/
	RequireSpecialCharacter interface{} `yaml:"requireSpecialCharacter,omitempty"`

	/*AccessTokenValiditySeconds - Descr: The access token validity for the default zone if nothing is configured on the client. Will override global validity policies for the default zone only. Default: 43200
*/
	AccessTokenValiditySeconds interface{} `yaml:"accessTokenValiditySeconds,omitempty"`

	/*RefreshTokenValiditySeconds - Descr: The refresh token validity for the default zone if nothing is configured on the client. Will override global validity policies for the default zone only. Default: 2592000
*/
	RefreshTokenValiditySeconds interface{} `yaml:"refreshTokenValiditySeconds,omitempty"`

	/*RequireDigit - Descr: Minimum number of digits required for password to be considered valid Default: 0
*/
	RequireDigit interface{} `yaml:"requireDigit,omitempty"`

	/*MaxLength - Descr: Maximum number of characters required for password to be considered valid Default: 255
*/
	MaxLength interface{} `yaml:"maxLength,omitempty"`

	/*RequireUpperCaseCharacter - Descr: Minimum number of uppercase characters required for password to be considered valid Default: 0
*/
	RequireUpperCaseCharacter interface{} `yaml:"requireUpperCaseCharacter,omitempty"`

	/*CountFailuresWithinSeconds - Descr: Number of seconds in which lockoutAfterFailures failures must occur in order for account to be locked Default: 3600
*/
	CountFailuresWithinSeconds interface{} `yaml:"countFailuresWithinSeconds,omitempty"`

	/*LockoutAfterFailures - Descr: Number of allowed failures before account is locked Default: 5
*/
	LockoutAfterFailures interface{} `yaml:"lockoutAfterFailures,omitempty"`

	/*LockoutPeriodSeconds - Descr: Number of seconds to lock out an account when lockoutAfterFailures failures is exceeded Default: 300
*/
	LockoutPeriodSeconds interface{} `yaml:"lockoutPeriodSeconds,omitempty"`

	/*ExpirePasswordInMonths - Descr: Number of months after which current password expires Default: 0
*/
	ExpirePasswordInMonths interface{} `yaml:"expirePasswordInMonths,omitempty"`

	/*RequireLowerCaseCharacter - Descr: Minimum number of lowercase characters required for password to be considered valid Default: 0
*/
	RequireLowerCaseCharacter interface{} `yaml:"requireLowerCaseCharacter,omitempty"`

	/*MinLength - Descr: Minimum number of characters required for password to be considered valid Default: 0
*/
	MinLength interface{} `yaml:"minLength,omitempty"`

	/*Keys - Descr: Map of key ids to key pairs (signing and verification keys) Default: <nil>
*/
	Keys interface{} `yaml:"keys,omitempty"`

	/*Global - Descr: Minimum number of characters required for password to be considered valid Default: 0
*/
	Global *Global `yaml:"global,omitempty"`

}