package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaJob struct {

	/*Env - Descr: The https_proxy across the VMs Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Login - Descr: Private key for the service provider certificate. Default: <nil>
*/
	Login *Login `yaml:"login,omitempty"`

	/*Uaa - Descr: Used with search-and-bind and search-and-compare. Password for the LDAP ID that performs a search of the LDAP tree for user information. Default: <nil>
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Uaadb - Descr: The list of database Roles used in UAA database including tag/name/password Default: <nil>
*/
	Uaadb *Uaadb `yaml:"uaadb,omitempty"`

	/*Domain - Descr: Deprecated. Use uaa.url for setting the location of UAA Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

}