package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaPassword struct {

	/*Policy - Descr: Minimum number of digits required for password to be considered valid Default: 0
*/
	Policy *PasswordPolicy `yaml:"policy,omitempty"`

}