package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type User struct {

	/*Authorities - Descr: Contains a list of the default authorities/scopes assigned to a user Default: [openid scim.me cloud_controller.read cloud_controller.write cloud_controller_service_permissions.read password.write uaa.user approvals.me oauth.approvals notification_preferences.read notification_preferences.write profile roles user_attributes]
*/
	Authorities interface{} `yaml:"authorities,omitempty"`

	/*Override - Descr: If true override users defined in uaa.scim.users found in the database. Default: true
*/
	Override interface{} `yaml:"override,omitempty"`

}