package debian_nfs_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DebianNfsServer struct {

	/*NfsServer - Descr: Pipefs directory for NFS idmapd Default: /var/lib/nfs/rpc_pipef
*/
	NfsServer *NfsServer `yaml:"nfs_server,omitempty"`

}