package dea_next 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StagingBandwidthLimit struct {

	/*Burst - Descr: Network bandwidth burst limit for staging tasks in bytes Default: <nil>
*/
	Burst interface{} `yaml:"burst,omitempty"`

	/*Rate - Descr: Network bandwidth limit for staging tasks in bytes per second Default: <nil>
*/
	Rate interface{} `yaml:"rate,omitempty"`

}