package aws_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AwsCpi struct {

	/*Blobstore - Descr: AWS S3 Bucket used by s3 blobstore plugin Default: <nil>
*/
	Blobstore *Blobstore `yaml:"blobstore,omitempty"`

	/*Registry - Descr: Password to access the Registry Default: <nil>
*/
	Registry *Registry `yaml:"registry,omitempty"`

	/*Nats - Descr: Port that the nats server listens on Default: 4222
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Env - Descr: Https proxy to connect to cloud API's Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Ntp - Descr: List of ntp server IPs. pool.ntp.org attempts to return IPs closest to your location, but you can still specify if needed. Default: [0.pool.ntp.org 1.pool.ntp.org]
*/
	Ntp interface{} `yaml:"ntp,omitempty"`

	/*Agent - Descr: Agent mbus Default: <nil>
*/
	Agent *Agent `yaml:"agent,omitempty"`

	/*Aws - Descr: AWS ELB service endpoint, without protocol/scheme (Optional: default endpoint will be constructed from region if not specified) Default: <nil>
*/
	Aws *Aws `yaml:"aws,omitempty"`

}