package photoncpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Actions struct {

	/*DisksDir - Descr: Directory where disks are stored Default: /var/vcap/store/cpi/disks
*/
	DisksDir interface{} `yaml:"disks_dir,omitempty"`

	/*HostPersistentBindMountsDir - Descr: Directory with sub-directories at which persistent disks are mounted on the host Default: /var/vcap/store/cpi/persistent_bind_mounts_dir
*/
	HostPersistentBindMountsDir interface{} `yaml:"host_persistent_bind_mounts_dir,omitempty"`

	/*GuestPersistentBindMountsDir - Descr: Directory with sub-directories at which persistent disks are mounted inside VMs Default: /photon-cpi-dev
*/
	GuestPersistentBindMountsDir interface{} `yaml:"guest_persistent_bind_mounts_dir,omitempty"`

	/*AgentEnvService - Descr: Type of Agent Env Service to use, e.g. registry or file Default: file
*/
	AgentEnvService interface{} `yaml:"agent_env_service,omitempty"`

	/*HostEphemeralBindMountsDir - Descr: Directory with sub-directories at which ephemeral disks are mounted on the host Default: /var/vcap/store/cpi/ephemeral_bind_mounts_dir
*/
	HostEphemeralBindMountsDir interface{} `yaml:"host_ephemeral_bind_mounts_dir,omitempty"`

	/*GuestEphemeralBindMountPath - Descr: Path at which ephemeral disk is mounted inside VMs Default: /var/vcap/data
*/
	GuestEphemeralBindMountPath interface{} `yaml:"guest_ephemeral_bind_mount_path,omitempty"`

	/*Registry - Descr: Password for registry Default: 
*/
	Registry *Registry `yaml:"registry,omitempty"`

	/*StemcellsDir - Descr: Directory where stemcells are stored Default: /var/vcap/store/cpi/stemcells
*/
	StemcellsDir interface{} `yaml:"stemcells_dir,omitempty"`

}