package photoncpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cpi struct {

	/*Actions - Descr: Type of Agent Env Service to use, e.g. registry or file Default: file
*/
	Actions *Actions `yaml:"actions,omitempty"`

	/*Agent - Descr: Options for the blobstore used by deployed BOSH agents Default: map[]
*/
	Agent *CpiAgent `yaml:"agent,omitempty"`

	/*HostIp - Descr: IP address of the host that will be used by containers, must be the same as mbus IP Default: <nil>
*/
	HostIp interface{} `yaml:"host_ip,omitempty"`

}