package photoncpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PhotoncpiJob struct {

	/*Blobstore - Descr: Provider type for the blobstore used by deployed BOSH agents (e.g. dav, s3) Default: 
*/
	Blobstore *Blobstore `yaml:"blobstore,omitempty"`

	/*Cpi - Descr: Type of Agent Env Service to use, e.g. registry or file Default: file
*/
	Cpi *Cpi `yaml:"cpi,omitempty"`

	/*Photon - Descr: Photon project Default: 
*/
	Photon *Photon `yaml:"photon,omitempty"`

	/*Agent - Descr: Mbus URL used by deployed BOSH agents Default: 
*/
	Agent *Agent `yaml:"agent,omitempty"`

	/*Ntp - Descr: ntp Default: 
*/
	Ntp interface{} `yaml:"ntp,omitempty"`

}