package photoncpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Registry struct {

	/*Password - Descr: Password for registry Default: 
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Port - Descr: Port of registry Default: 6301
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Host - Descr: Hostname of registry Default: 
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Username - Descr: Username for registry Default: 
*/
	Username interface{} `yaml:"username,omitempty"`

}