package vault_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Backend struct {

	/*Advertise - Descr: The address to hand out to bound applications, along with their credentials.  Defaults to `vault.broker.backend.address`. Default: 
*/
	Advertise interface{} `yaml:"advertise,omitempty"`

	/*Token - Descr: The token that the service broker will use when interacting with the Vault. Default: <nil>
*/
	Token interface{} `yaml:"token,omitempty"`

	/*SkipVerify - Descr: Instructs the broker to ignore SSL/TLS certificate problems (self-signedness, domain mismatch, expiration, etc.). Set this at your own risk. Default: false
*/
	SkipVerify interface{} `yaml:"skip_verify,omitempty"`

	/*Address - Descr: The address to use when accessing the Vault to set up new policies and manage provisioned services. Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

}