package vault_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Guid - Descr: A unique GUID to use for this service broker inside of Cloud Foundry. Default: 
*/
	Guid interface{} `yaml:"guid,omitempty"`

	/*Username - Descr: The username for authenticating interaction with Cloud Foundry. Default: vault
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Service - Descr: Name of the service, as shown in the marketplace. Default: vault
*/
	Service *Service `yaml:"service,omitempty"`

	/*Backend - Descr: The address to use when accessing the Vault to set up new policies and manage provisioned services. Default: <nil>
*/
	Backend *Backend `yaml:"backend,omitempty"`

	/*Password - Descr: The password for authenticating interaction with Cloud Foundry. Default: vault
*/
	Password interface{} `yaml:"password,omitempty"`

}