package nats 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NatsJob struct {

	/*Nats - Descr: Port for pprof. 0 means disabled. Default: 0
*/
	Nats *Nats `yaml:"nats,omitempty"`

}