package haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cc struct {

	/*AllowAppSshAccess - Descr: Allow users to change the value of the app-level allow_ssh attribute Default: true
*/
	AllowAppSshAccess interface{} `yaml:"allow_app_ssh_access,omitempty"`

}