package blobstore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Tls struct {

	/*Port - Descr: The TCP port on which the internal blobstore server listens Default: 443
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Cert - Descr: The PEM-encoded certificate (optionally as a certificate chain) for serving blobs over TLS/SSL Default: <nil>
*/
	Cert interface{} `yaml:"cert,omitempty"`

	/*PrivateKey - Descr: The PEM-encoded private key for signing TLS/SSL traffic Default: <nil>
*/
	PrivateKey interface{} `yaml:"private_key,omitempty"`

}