package registry 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Registry struct {

	/*Openstack - Descr: OpenStack endpoint type (optional, by default publicURL) Default: publicURL
*/
	Openstack *Openstack `yaml:"openstack,omitempty"`

	/*Http - Descr: TCP port Registry daemon listens on Default: 25777
*/
	Http *Http `yaml:"http,omitempty"`

	/*Db - Descr: The type of database used Default: postgres
*/
	Db *Db `yaml:"db,omitempty"`

	/*Registry - Descr: The type of database used Default: postgres
*/
	Registry *Registry `yaml:"registry,omitempty"`

	/*Env - Descr: List of comma-separated hosts that should skip connecting to the proxy in the registry Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Aws - Descr: The path the a CA cert directory Default: <nil>
*/
	Aws *Aws `yaml:"aws,omitempty"`

}