package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTestsJob struct {

	/*AcceptanceTests - Descr: Flag to include the route services tests. Diego must be deployed for these tests to pass. Default: false
*/
	AcceptanceTests *AcceptanceTests `yaml:"acceptance_tests,omitempty"`

}