package consul 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConsulJob struct {

	/*Networks - Descr: Deployment's internal name for the network interface to discover own IP Default: <nil>
*/
	Networks *Networks `yaml:"networks,omitempty"`

	/*Consul - Descr: The content of the ca file Default: <nil>
*/
	Consul *Consul `yaml:"consul,omitempty"`

}