package consul 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Networks struct {

	/*Apps - Descr: Deployment's internal name for the network interface to discover own IP Default: <nil>
*/
	Apps interface{} `yaml:"apps,omitempty"`

}