package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Clients struct {

	/*Gorouter - Descr: Password for UAA client for the gorouter. Default: <nil>
*/
	Gorouter *Gorouter `yaml:"gorouter,omitempty"`

}