package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ssl struct {

	/*Port - Descr: Secure Port on which UAA is running. Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

}