package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Uaa struct {

	/*Clients - Descr: Password for UAA client for the gorouter. Default: <nil>
*/
	Clients *Clients `yaml:"clients,omitempty"`

	/*Port - Descr: Port on which UAA is running. Default: 8080
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Ssl - Descr: Secure Port on which UAA is running. Default: <nil>
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}