package nsync 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*Nsync - Descr: URL of file server Default: http://file-server.service.cf.internal:8080
*/
	Nsync *Nsync `yaml:"nsync,omitempty"`

}