package nsync 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NsyncJob struct {

	/*Diego - Descr: URL of file server Default: http://file-server.service.cf.internal:8080
*/
	Diego *Diego `yaml:"diego,omitempty"`

}