package statsd_injector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StatsdInjector struct {

	/*MetronPort - Descr: The port on which metron is running Default: 3457
*/
	MetronPort interface{} `yaml:"metron_port,omitempty"`

	/*StatsdPort - Descr: The port on which the injector should listen for statsd messages Default: 8125
*/
	StatsdPort interface{} `yaml:"statsd_port,omitempty"`

	/*LogLevel - Descr: The log level for the statsd injector Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

}