package statsd_injector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StatsdInjectorJob struct {

	/*StatsdInjector - Descr: The log level for the statsd injector Default: info
*/
	StatsdInjector *StatsdInjector `yaml:"statsd_injector,omitempty"`

}