package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RedisBroker struct {

	/*ServiceName - Descr: Service name Default: p-redis
*/
	ServiceName interface{} `yaml:"service_name,omitempty"`

}