package etcd 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdJob struct {

	/*Etcd - Descr: Information about etcd cluster Default: <nil>
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

}