package powerdns 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Dns struct {

	/*DistributorThreads - Descr: Number of threads to query the backend, for each receiver thread Default: 2
*/
	DistributorThreads interface{} `yaml:"distributor_threads,omitempty"`

	/*Recursor - Descr: If recursion is desired, IP address of a recursing nameserver (optional) Default: <nil>
*/
	Recursor interface{} `yaml:"recursor,omitempty"`

	/*Db - Descr: Adapter for the PowerDNS database connection Default: postgres
*/
	Db *Db `yaml:"db,omitempty"`

	/*ReceiverThreads - Descr: Number of sockets the powerdns process will open Default: 2
*/
	ReceiverThreads interface{} `yaml:"receiver_threads,omitempty"`

	/*Address - Descr: Address of the primary PowerDNS instance Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Webserver - Descr: Password clients must use to access PowerDNS webserver (optional) Default: <nil>
*/
	Webserver *Webserver `yaml:"webserver,omitempty"`

	/*QueryLocalAddress - Descr: IP address to use as a source address for sending queries (optional; useful with multiple IP addresses) Default: <nil>
*/
	QueryLocalAddress interface{} `yaml:"query_local_address,omitempty"`

	/*LocalAddress - Descr: IP address to which to bind to (optional; useful with multiple IP addresses) Default: <nil>
*/
	LocalAddress interface{} `yaml:"local_address,omitempty"`

}