package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AppSsh struct {

	/*OauthClientId - Descr: The oauth client ID of the SSH proxy Default: ssh-proxy
*/
	OauthClientId interface{} `yaml:"oauth_client_id,omitempty"`

	/*HostKeyFingerprint - Descr: Fingerprint of the host key of the SSH proxy that brokers connections to application instances Default: <nil>
*/
	HostKeyFingerprint interface{} `yaml:"host_key_fingerprint,omitempty"`

	/*Port - Descr: External port for SSH access to application instances Default: 2222
*/
	Port interface{} `yaml:"port,omitempty"`

}