package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BlobstoreUpload struct {

	/*TimeoutInSeconds - Descr: The longest this job can take before it is cancelled Default: <nil>
*/
	TimeoutInSeconds interface{} `yaml:"timeout_in_seconds,omitempty"`

}