package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cc struct {

	/*Renderer - Descr: Maximum number of results returned per page Default: 100
*/
	Renderer *Renderer `yaml:"renderer,omitempty"`

	/*DefaultToDiegoBackend - Descr: Use Diego backend by default for new apps Default: false
*/
	DefaultToDiegoBackend interface{} `yaml:"default_to_diego_backend,omitempty"`

	/*CcPartition - Descr: Deprecated. Defines a 'partition' for the health_manager job Default: default
*/
	CcPartition interface{} `yaml:"cc_partition,omitempty"`

	/*ExternalProtocol - Descr: The protocol used to access the CC API from an external entity Default: https
*/
	ExternalProtocol interface{} `yaml:"external_protocol,omitempty"`

	/*StagingUploadPassword - Descr: User's password used to access internal endpoints of Cloud Controller to upload files when staging Default: 
*/
	StagingUploadPassword interface{} `yaml:"staging_upload_password,omitempty"`

	/*DefaultRunningSecurityGroups - Descr: The default running security groups that will be seeded in CloudController. Default: <nil>
*/
	DefaultRunningSecurityGroups interface{} `yaml:"default_running_security_groups,omitempty"`

	/*AuditEvents - Descr: How old an audit event should stay in cloud controller database before being cleaned up Default: 31
*/
	AuditEvents *AuditEvents `yaml:"audit_events,omitempty"`

	/*AppEvents - Descr: How old an app event should stay in cloud controller database before being cleaned up Default: 31
*/
	AppEvents *AppEvents `yaml:"app_events,omitempty"`

	/*DefaultHealthCheckTimeout - Descr: Default health check timeout (in seconds) that can be set for the app Default: 60
*/
	DefaultHealthCheckTimeout interface{} `yaml:"default_health_check_timeout,omitempty"`

	/*DefaultStack - Descr: The default stack to use if no custom stack is specified by an app. Default: cflinuxfs2
*/
	DefaultStack interface{} `yaml:"default_stack,omitempty"`

	/*InternalApiUser - Descr: User name used by Diego to access internal endpoints Default: internal_user
*/
	InternalApiUser interface{} `yaml:"internal_api_user,omitempty"`

	/*SecurityGroupDefinitions - Descr: Array of security groups that will be seeded into CloudController. Default: <nil>
*/
	SecurityGroupDefinitions interface{} `yaml:"security_group_definitions,omitempty"`

	/*DisableCustomBuildpacks - Descr: Disable external (i.e. git) buildpacks? (Admin buildpacks and system buildpacks only.) Default: false
*/
	DisableCustomBuildpacks interface{} `yaml:"disable_custom_buildpacks,omitempty"`

	/*AppBitsUploadGracePeriodInSeconds - Descr: Extra token expiry time while uploading big apps. Default: 1200
*/
	AppBitsUploadGracePeriodInSeconds interface{} `yaml:"app_bits_upload_grace_period_in_seconds,omitempty"`

	/*DbEncryptionKey - Descr: key for encrypting sensitive values in the CC database Default: 
*/
	DbEncryptionKey interface{} `yaml:"db_encryption_key,omitempty"`

	/*ExternalPort - Descr: External Cloud Controller port Default: 9022
*/
	ExternalPort interface{} `yaml:"external_port,omitempty"`

	/*PlacementTopStagerPercentage - Descr: The percentage of top stagers considered when choosing a stager Default: 10
*/
	PlacementTopStagerPercentage interface{} `yaml:"placement_top_stager_percentage,omitempty"`

	/*StagingUploadUser - Descr: User name used to access internal endpoints of Cloud Controller to upload files when staging Default: 
*/
	StagingUploadUser interface{} `yaml:"staging_upload_user,omitempty"`

	/*UsersCanSelectBackend - Descr: Allow non-admin users to switch their apps between DEA and Diego backends Default: true
*/
	UsersCanSelectBackend interface{} `yaml:"users_can_select_backend,omitempty"`

	/*FailedJobs - Descr: How old a failed job should stay in cloud controller database before being cleaned up Default: 31
*/
	FailedJobs *FailedJobs `yaml:"failed_jobs,omitempty"`

	/*DevelopmentMode - Descr: Enable development features for monitoring and insight Default: false
*/
	DevelopmentMode interface{} `yaml:"development_mode,omitempty"`

	/*Buildpacks - Descr: Fog connection hash Default: <nil>
*/
	Buildpacks *Buildpacks `yaml:"buildpacks,omitempty"`

	/*BrokerClientMaxAsyncPollDurationMinutes - Descr: The max duration the CC will fetch service instance state from a service broker (in minutes). Default is 1 week Default: 10080
*/
	BrokerClientMaxAsyncPollDurationMinutes interface{} `yaml:"broker_client_max_async_poll_duration_minutes,omitempty"`

	/*QuotaDefinitions - Descr: Hash of default quota definitions to be used during Cloud Controller database seeding. After seeding, these can be updated using the API but not using the manifest. Default: <nil>
*/
	QuotaDefinitions interface{} `yaml:"quota_definitions,omitempty"`

	/*StatsdPort - Descr: The port for the statsd server, defaults to the local metron agent Default: 8125
*/
	StatsdPort interface{} `yaml:"statsd_port,omitempty"`

	/*InstanceFileDescriptorLimit - Descr: The file descriptors made available to each app instance Default: 16384
*/
	InstanceFileDescriptorLimit interface{} `yaml:"instance_file_descriptor_limit,omitempty"`

	/*InternalServiceHostname - Descr: Internal hostname used to resolve the address of the Cloud Controller Default: cloud-controller-ng.service.cf.internal
*/
	InternalServiceHostname interface{} `yaml:"internal_service_hostname,omitempty"`

	/*DefaultAppMemory - Descr: How much memory given to an app if not specified Default: 1024
*/
	DefaultAppMemory interface{} `yaml:"default_app_memory,omitempty"`

	/*DbLoggingLevel - Descr: Log level for cc database operations Default: debug2
*/
	DbLoggingLevel interface{} `yaml:"db_logging_level,omitempty"`

	/*Jobs - Descr: The longest this job can take before it is cancelled Default: <nil>
*/
	Jobs *Jobs `yaml:"jobs,omitempty"`

	/*BulkApiUser - Descr: User used to access the bulk_api, health_manager uses it to connect to the cc, announced over NATS Default: bulk_api
*/
	BulkApiUser interface{} `yaml:"bulk_api_user,omitempty"`

	/*StatsdHost - Descr: The host for the statsd server, defaults to the local metron agent Default: 127.0.0.1
*/
	StatsdHost interface{} `yaml:"statsd_host,omitempty"`

	/*AppBitsMaxBodySize - Descr: Maximum body size for nginx bits uploads Default: 1536M
*/
	AppBitsMaxBodySize interface{} `yaml:"app_bits_max_body_size,omitempty"`

	/*ExternalHost - Descr: Host part of the cloud_controller api URI, will be joined with value of 'domain' Default: api
*/
	ExternalHost interface{} `yaml:"external_host,omitempty"`

	/*ClientMaxBodySize - Descr: Maximum body size for nginx Default: 15M
*/
	ClientMaxBodySize interface{} `yaml:"client_max_body_size,omitempty"`

	/*MinRecommendedCliVersion - Descr: Minimum recommended version of the CF CLI. Default: <nil>
*/
	MinRecommendedCliVersion interface{} `yaml:"min_recommended_cli_version,omitempty"`

	/*StagingTimeoutInSeconds - Descr: Timeout for staging a droplet Default: 900
*/
	StagingTimeoutInSeconds interface{} `yaml:"staging_timeout_in_seconds,omitempty"`

	/*DefaultQuotaDefinition - Descr: Local to use a local (NFS) file system.  AWS to use AWS. Default: default
*/
	DefaultQuotaDefinition interface{} `yaml:"default_quota_definition,omitempty"`

	/*AllowedCorsDomains - Descr: List of domains (including scheme) from which Cross-Origin requests will be accepted, a * can be used as a wildcard for any part of a domain Default: []
*/
	AllowedCorsDomains interface{} `yaml:"allowed_cors_domains,omitempty"`

	/*Droplets - Descr: Fog connection hash Default: <nil>
*/
	Droplets *Droplets `yaml:"droplets,omitempty"`

	/*AppUsageEvents - Descr: How old an app usage event should stay in cloud controller database before being cleaned up Default: 31
*/
	AppUsageEvents *AppUsageEvents `yaml:"app_usage_events,omitempty"`

	/*NginxAccessLogDestination - Descr: The nginx access log destination. This can be used to route access logs to a file, syslog, or a memory buffer. Default: /var/vcap/sys/log/nginx_cc/nginx.access.log
*/
	NginxAccessLogDestination interface{} `yaml:"nginx_access_log_destination,omitempty"`

	/*BrokerClientTimeoutSeconds - Descr: For requests to service brokers, this is the HTTP (open and read) timeout setting. Default: 60
*/
	BrokerClientTimeoutSeconds interface{} `yaml:"broker_client_timeout_seconds,omitempty"`

	/*Thresholds - Descr: The cc will restart if memory remains above this threshold for 3 monit cycles Default: 3750
*/
	Thresholds *Thresholds `yaml:"thresholds,omitempty"`

	/*FlappingCrashCountThreshold - Descr: The threshold of crashes after which the app is marked as flapping Default: 3
*/
	FlappingCrashCountThreshold interface{} `yaml:"flapping_crash_count_threshold,omitempty"`

	/*Stacks - Descr: Tag used by the DEA to describe capabilities (i.e. 'Windows7', 'python-linux'). DEA and CC must agree. Default: [map[name:cflinuxfs2 description:Cloud Foundry Linux-based filesystem]]
*/
	Stacks interface{} `yaml:"stacks,omitempty"`

	/*ServiceUsageEvents - Descr: How old a service usage event should stay in cloud controller database before being cleaned up Default: 31
*/
	ServiceUsageEvents *ServiceUsageEvents `yaml:"service_usage_events,omitempty"`

	/*StagingFileDescriptorLimit - Descr: File descriptor limit for staging tasks Default: 16384
*/
	StagingFileDescriptorLimit interface{} `yaml:"staging_file_descriptor_limit,omitempty"`

	/*LoggingLevel - Descr: Log level for cc Default: debug2
*/
	LoggingLevel interface{} `yaml:"logging_level,omitempty"`

	/*AllowAppSshAccess - Descr: Allow users to change the value of the app-level allow_ssh attribute Default: true
*/
	AllowAppSshAccess interface{} `yaml:"allow_app_ssh_access,omitempty"`

	/*CompletedTasks - Descr: How long a completed task will stay in cloud controller database before being cleaned up based on last updated time with success or failure. Default: 31
*/
	CompletedTasks *CompletedTasks `yaml:"completed_tasks,omitempty"`

	/*MaximumAppDiskInMb - Descr: The maximum amount of disk a user can request Default: 2048
*/
	MaximumAppDiskInMb interface{} `yaml:"maximum_app_disk_in_mb,omitempty"`

	/*NginxAccessLogFormat - Descr: The nginx log format string to use when writing to the access log. Default: $host - [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" $proxy_add_x_forwarded_for vcap_request_id:$upstream_http_x_vcap_request_id response_time:$upstream_response_time

*/
	NginxAccessLogFormat interface{} `yaml:"nginx_access_log_format,omitempty"`

	/*Directories - Descr: The directory to use for temporary files Default: /var/vcap/data/cloud_controller_ng/tmp
*/
	Directories *Directories `yaml:"directories,omitempty"`

	/*BrokerClientDefaultAsyncPollIntervalSeconds - Descr: Specifies interval on which the CC will poll a service broker for asynchronous actions. If the service broker provides a value, this value is the minimum accepted value the broker can provide. Default: 60
*/
	BrokerClientDefaultAsyncPollIntervalSeconds interface{} `yaml:"broker_client_default_async_poll_interval_seconds,omitempty"`

	/*BulkApiPassword - Descr: Password used to access the bulk_api, health_manager uses it to connect to the cc, announced over NATS Default: <nil>
*/
	BulkApiPassword interface{} `yaml:"bulk_api_password,omitempty"`

	/*DeaUseHttps - Descr: enable ssl for communication with DEAs Default: false
*/
	DeaUseHttps interface{} `yaml:"dea_use_https,omitempty"`

	/*Info - Descr: Custom attribute keys and values for /v2/info endpoint Default: <nil>
*/
	Info *Info `yaml:"info,omitempty"`

	/*Packages - Descr: URI for a CDN to used for app package downloads Default: 
*/
	Packages *Packages `yaml:"packages,omitempty"`

	/*FeatureDisabledMessage - Descr: Custom message to use for a disabled feature. Default: <nil>
*/
	FeatureDisabledMessage interface{} `yaml:"feature_disabled_message,omitempty"`

	/*MinCliVersion - Descr: Minimum version of the CF CLI to work with the API. Default: <nil>
*/
	MinCliVersion interface{} `yaml:"min_cli_version,omitempty"`

	/*CoreFilePattern - Descr: Filename template for core dump files. Use an empty string if you don't want core files saved. Default: /var/vcap/sys/cores/core-%e-%s-%p-%t
*/
	CoreFilePattern interface{} `yaml:"core_file_pattern,omitempty"`

	/*DefaultAppDiskInMb - Descr: The default disk space an app gets Default: 1024
*/
	DefaultAppDiskInMb interface{} `yaml:"default_app_disk_in_mb,omitempty"`

	/*ResourcePool - Descr: Fog connection hash Default: <nil>
*/
	ResourcePool *ResourcePool `yaml:"resource_pool,omitempty"`

	/*SecurityEventLogging - Descr: Enable logging of all requests made to the Cloud Controller in CEF format. Default: false
*/
	SecurityEventLogging *SecurityEventLogging `yaml:"security_event_logging,omitempty"`

	/*UaaResourceId - Descr: Name of service to register to UAA Default: cloud_controller,cloud_controller_service_permissions
*/
	UaaResourceId interface{} `yaml:"uaa_resource_id,omitempty"`

	/*MaximumHealthCheckTimeout - Descr: Maximum health check timeout (in seconds) that can be set for the app Default: 180
*/
	MaximumHealthCheckTimeout interface{} `yaml:"maximum_health_check_timeout,omitempty"`

	/*DefaultStagingSecurityGroups - Descr: The default staging security groups that will be seeded in CloudController. Default: <nil>
*/
	DefaultStagingSecurityGroups interface{} `yaml:"default_staging_security_groups,omitempty"`

	/*LoggingMaxRetries - Descr: Passthru value for Steno logger Default: 1
*/
	LoggingMaxRetries interface{} `yaml:"logging_max_retries,omitempty"`

	/*NginxErrorLogLevel - Descr: The lowest severity nginx log level to capture in the error log. Default: error
*/
	NginxErrorLogLevel interface{} `yaml:"nginx_error_log_level,omitempty"`

	/*NginxErrorLogDestination - Descr: The nginx error log destination. This can be used to route error logs to a file, syslog, or a memory buffer. Default: /var/vcap/sys/log/nginx_cc/nginx.error.log
*/
	NginxErrorLogDestination interface{} `yaml:"nginx_error_log_destination,omitempty"`

	/*Diego - Descr: URL of the Diego stager service Default: http://stager.service.cf.internal:8888
*/
	Diego *Diego `yaml:"diego,omitempty"`

	/*Newrelic - Descr: The api key for NewRelic Default: <nil>
*/
	Newrelic *Newrelic `yaml:"newrelic,omitempty"`

	/*ReservedPrivateDomains - Descr: File location of a list of reserved private domains (for file format, see https://publicsuffix.org/) Default: <nil>
*/
	ReservedPrivateDomains interface{} `yaml:"reserved_private_domains,omitempty"`

	/*InstallBuildpacks - Descr: Set of buildpacks to install during deploy Default: <nil>
*/
	InstallBuildpacks interface{} `yaml:"install_buildpacks,omitempty"`

	/*DefaultFogConnection - Descr: Local root when fog provider is not overridden (should be an NFS mount if using more than one cloud controller) Default: /var/vcap/nfs/shared
*/
	DefaultFogConnection *DefaultFogConnection `yaml:"default_fog_connection,omitempty"`

	/*InternalApiPassword - Descr: Password used by Diego to access internal endpoints Default: <nil>
*/
	InternalApiPassword interface{} `yaml:"internal_api_password,omitempty"`

}