package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CcRouting struct {

	/*Secret - Descr: Used for fetching routing information from the Routing API Default: <nil>
*/
	Secret interface{} `yaml:"secret,omitempty"`

}