package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CloudControllerUsernameLookup struct {

	/*Secret - Descr: Used for fetching usernames from UAA. Default: <nil>
*/
	Secret interface{} `yaml:"secret,omitempty"`

}