package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Directories struct {

	/*Diagnostics - Descr: The directory where operator requested diagnostic files should be placed Default: /var/vcap/data/cloud_controller_ng/diagnostics
*/
	Diagnostics interface{} `yaml:"diagnostics,omitempty"`

	/*Tmpdir - Descr: The directory to use for temporary files Default: /var/vcap/data/cloud_controller_ng/tmp
*/
	Tmpdir interface{} `yaml:"tmpdir,omitempty"`

}