package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Droplets struct {

	/*Cdn - Descr: Private key for signing download URIs Default: 
*/
	Cdn *Cdn `yaml:"cdn,omitempty"`

	/*FogConnection - Descr: Fog connection hash Default: <nil>
*/
	FogConnection interface{} `yaml:"fog_connection,omitempty"`

	/*MaxStagedDropletsStored - Descr: Number of recent, staged droplets stored per app (not including current droplet) Default: 5
*/
	MaxStagedDropletsStored interface{} `yaml:"max_staged_droplets_stored,omitempty"`

	/*DropletDirectoryKey - Descr: Directory (bucket) used store droplets.  It does not have be pre-created. Default: cc-droplets
*/
	DropletDirectoryKey interface{} `yaml:"droplet_directory_key,omitempty"`

	/*WebdavConfig - Descr: The basic auth password that CC uses to connect to the admin endpoint on webdav Default: 
*/
	WebdavConfig *WebdavConfig `yaml:"webdav_config,omitempty"`

	/*BlobstoreType - Descr: The type of blobstore backing to use. Valid values: ['fog', 'webdav'] Default: fog
*/
	BlobstoreType interface{} `yaml:"blobstore_type,omitempty"`

}