package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Info struct {

	/*Custom - Descr: Custom attribute keys and values for /v2/info endpoint Default: <nil>
*/
	Custom interface{} `yaml:"custom,omitempty"`

}