package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Local struct {

	/*NumberOfWorkers - Descr: Number of local cloud_controller_worker workers Default: 2
*/
	NumberOfWorkers interface{} `yaml:"number_of_workers,omitempty"`

}