package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Router struct {

	/*RouteServicesSecret - Descr: Support for route services is disabled when no value is configured. Default: 
*/
	RouteServicesSecret interface{} `yaml:"route_services_secret,omitempty"`

}