package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SecurityEventLogging struct {

	/*Enabled - Descr: Enable logging of all requests made to the Cloud Controller in CEF format. Default: false
*/
	Enabled interface{} `yaml:"enabled,omitempty"`

}