package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Thresholds struct {

	/*Api - Descr: The cc will alert if memory remains above this threshold for 3 monit cycles Default: 3500
*/
	Api *Api `yaml:"api,omitempty"`

}