package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*Blobstore - Descr: AWS KMS key ID to use for object encryption. All GET and PUT requests for an object protected by AWS KMS will fail if not made via SSL or using SigV4. Default: <nil>
*/
	Blobstore *AgentBlobstore `yaml:"blobstore,omitempty"`

	/*Nats - Descr: Address for agent to connect to nats Default: <nil>
*/
	Nats *AgentNats `yaml:"nats,omitempty"`

}