package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BlobstoreDirector struct {

	/*Password - Descr: Password director uses to connect to blobstore used by simple blobstore plugin Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*User - Descr: Username director uses to connect to blobstore used by simple blobstore plugin Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

}