package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CompiledPackageCache struct {

	/*Options - Descr: Signature version of the blobstore used by s3 blobstore plugin (optional, if not provided the s3 client decides which version to use) Default: <nil>
*/
	Options *Options `yaml:"options,omitempty"`

	/*Provider - Descr: Provider of the blobstore used for the compiled package cache Default: s3
*/
	Provider interface{} `yaml:"provider,omitempty"`

}