package director

/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
 */
type Director struct {

	/*Address - Descr: Address of the Bosh Director to connect to Default: <nil>
	 */
	Address interface{} `yaml:"address,omitempty"`

	/*EnableSnapshots - Descr: Enable/Disable snapshots for persistent disks (true|false) Default: false
	 */
	EnableSnapshots interface{} `yaml:"enable_snapshots,omitempty"`

	/*CpiJob - Descr: Name of cpi job (null to use bundled cpi gems) Default: <nil>
	 */
	CpiJob interface{} `yaml:"cpi_job,omitempty"`

	/*Nginx - Descr: Prefer server's cipher priority instead of client's (true for On, false for Off) Default: true
	 */
	Nginx *Nginx `yaml:"nginx,omitempty"`

	/*ConfigServerUrl - Descr: URL for the config server Default: http://127.0.0.1:8080
	 */
	ConfigServerUrl interface{} `yaml:"config_server_url,omitempty"`

	/*RemoveDevTools - Descr: When true, remove dev tool packages from non-compilation VMs Default: false
	 */
	RemoveDevTools interface{} `yaml:"remove_dev_tools,omitempty"`

	/*BackendPort - Descr: Port that the director listens on Default: 25556
	 */
	BackendPort interface{} `yaml:"backend_port,omitempty"`

	/*Name - Descr: Name of the director Default: <nil>
	 */
	Name interface{} `yaml:"name,omitempty"`

	/*Timeout - Descr: Timeout for connection from bosh CLI to nginx Default: 7200
	 */
	Timeout interface{} `yaml:"timeout,omitempty"`

	/*MaxVmCreateTries - Descr: Max retries when creating VMs Default: 5
	 */
	MaxVmCreateTries interface{} `yaml:"max_vm_create_tries,omitempty"`

	/*MaxUploadSize - Descr: Max allowed file size for upload Default: 10000m
	 */
	MaxUploadSize interface{} `yaml:"max_upload_size,omitempty"`

	/*Events - Descr: Max number of events to keep Default: 10000
	 */
	Events *Events `yaml:"events,omitempty"`

	/*MaxTasks - Descr: Max number of tasks per each type to keep in disk Default: 100
	 */
	MaxTasks interface{} `yaml:"max_tasks,omitempty"`

	/*Ssl - Descr: SSL private key for director (PEM encoded) Default: <nil>
	 */
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*MaxThreads - Descr: Max number of director concurrent threads Default: 32
	 */
	MaxThreads interface{} `yaml:"max_threads,omitempty"`

	/*Port - Descr: Port that the director nginx listens on Default: 25555
	 */
	Port interface{} `yaml:"port,omitempty"`

	/*Db - Descr: The type of database used (mysql2|postgres|sqlite) Default: postgres
	 */
	Db *DirectorDb `yaml:"db,omitempty"`

	/*SelfSnapshotSchedule - Descr: RufusScheduler cron formatted schedule for self snapshots Default: 0 0 6 * * * UTC
	 */
	SelfSnapshotSchedule interface{} `yaml:"self_snapshot_schedule,omitempty"`

	/*ParseConfigValues - Descr: When true, replace substitution values in manifest with values from config server Default: false
	 */
	ParseConfigValues interface{} `yaml:"parse_config_values,omitempty"`

	/*Encryption - Descr: Enable/Disable agent-director encryption (true|false) Default: false
	 */
	Encryption interface{} `yaml:"encryption,omitempty"`

	/*Debug - Descr: When a bosh deploy fails, the failed VM will be kept instead of destroyed Default: false
	 */
	Debug *Debug `yaml:"debug,omitempty"`

	/*SnapshotSchedule - Descr: RufusScheduler cron formatted schedule for snapshots Default: 0 0 7 * * * UTC
	 */
	SnapshotSchedule interface{} `yaml:"snapshot_schedule,omitempty"`

	/*Disks - Descr: RufusScheduler cron formatted schedule for cleanup of orphaned disks and orphaned snapshots Default: 0 0,30 * * * * UTC
	 */
	Disks *Disks `yaml:"disks,omitempty"`

	/*FlushArp - Descr: Clear up arp entries when machines are recreated Default: false
	 */
	FlushArp interface{} `yaml:"flush_arp,omitempty"`

	/*ProxyTimeout - Descr: Timeout for proxy connection from nginx to director Default: 900
	 */
	ProxyTimeout interface{} `yaml:"proxy_timeout,omitempty"`

	/*EnableDedicatedStatusWorker - Descr: Separate worker for 'bosh vms' and 'bosh ssh' Default: false
	 */
	EnableDedicatedStatusWorker interface{} `yaml:"enable_dedicated_status_worker,omitempty"`

	/*BackupSchedule - Descr: RufusScheduler cron formatted schedule for backups Default: <nil>
	 */
	BackupSchedule interface{} `yaml:"backup_schedule,omitempty"`

	/*AutoFixStatefulNodes - Descr: Enable/Disable auto resolution for stateful nodes for scan_and_fix (true|false) Default: true
	 */
	AutoFixStatefulNodes interface{} `yaml:"auto_fix_stateful_nodes,omitempty"`

	/*EnableVirtualDeleteVms - Descr: When true, bosh will not delete vm from cloud when instance update, just destroy vm record in db Default: false
	 */
	EnableVirtualDeleteVms interface{} `yaml:"enable_virtual_delete_vms,omitempty"`

	/*TrustedCerts - Descr: Cerfiticates that VMs created by this director should trust in addition to those packaged with the stemcell (PEM encoded; zero or more certs allowed) Default:
	 */
	TrustedCerts interface{} `yaml:"trusted_certs,omitempty"`

	/*Workers - Descr: Number of director workers Default: 3
	 */
	Workers interface{} `yaml:"workers,omitempty"`

	/*GenerateVmPasswords - Descr: When true, a random unique password will be used for each vm if user has not specified a password Default: false
	 */
	GenerateVmPasswords interface{} `yaml:"generate_vm_passwords,omitempty"`

	/*EnablePostDeploy - Descr: When true, all templates will run their post_deploy script once deployment is complete Default: false
	 */
	EnablePostDeploy interface{} `yaml:"enable_post_deploy,omitempty"`

	/*UserManagement - Descr: Symmetric key to verify Uaa token Default: <nil>
	 */
	UserManagement *UserManagement `yaml:"user_management,omitempty"`

	/*IgnoreMissingGateway - Descr: Allow gateway to be omitted from subnet configuration. Boshlite vms(containers) do not require gateway. Default: false
	 */
	IgnoreMissingGateway interface{} `yaml:"ignore_missing_gateway,omitempty"`

	/*DefaultSshOptions - Descr: Default user to use with bosh ssh command Default: vcap
	 */
	DefaultSshOptions *DefaultSshOptions `yaml:"default_ssh_options,omitempty"`

	/*BackupDestination - Descr: Configuration of the blobstore used by director for backups (dav|simple|s3) Default: <nil>
	 */
	BackupDestination interface{} `yaml:"backup_destination,omitempty"`

	/*LogAccessEventsToSyslog - Descr: Access to api is logged to the syslog Default: false
	 */
	LogAccessEventsToSyslog interface{} `yaml:"log_access_events_to_syslog,omitempty"`
}
