package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DnsDb struct {

	/*Host - Descr: DNS Database host Default: 127.0.0.1
*/
	Host interface{} `yaml:"host,omitempty"`

	/*User - Descr: DNS Database user Default: bosh
*/
	User interface{} `yaml:"user,omitempty"`

	/*Database - Descr: Name of the powerdns database Default: bosh
*/
	Database interface{} `yaml:"database,omitempty"`

	/*ConnectionOptions - Descr: Additional options for the powerdns database Default: map[max_connections:32 pool_timeout:10]
*/
	ConnectionOptions interface{} `yaml:"connection_options,omitempty"`

	/*Adapter - Descr: DNS Database adapter Default: postgres
*/
	Adapter interface{} `yaml:"adapter,omitempty"`

	/*Password - Descr: DNS Database password Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Port - Descr: Port that the powerdns database listens on Default: 5432
*/
	Port interface{} `yaml:"port,omitempty"`

}