package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Registry struct {

	/*Address - Descr: Address of the Registry to connect to Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Http - Descr: User to access the Registry Default: <nil>
*/
	Http *Http `yaml:"http,omitempty"`

}