package route_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*RouteEmitter - Descr: local metron agent's port Default: 3457
*/
	RouteEmitter *RouteEmitter `yaml:"route_emitter,omitempty"`

}