package route_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RouteEmitterJob struct {

	/*Diego - Descr: enable ssl for all communication with the bbs Default: true
*/
	Diego *Diego `yaml:"diego,omitempty"`

}