package registry 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Registry struct {

	/*Http - Descr: Username clients must use to access Registry via HTTP Basic Auth Default: <nil>
*/
	Http *Http `yaml:"http,omitempty"`

	/*Db - Descr: Name of the registry database Default: bosh_registry
*/
	Db *Db `yaml:"db,omitempty"`

}