package powerdns 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Db struct {

	/*User - Descr: User for the PowerDNS database connection Default: bosh
*/
	User interface{} `yaml:"user,omitempty"`

	/*Port - Descr: Port for the PowerDNS database connection Default: 5432
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Adapter - Descr: Adapter for the PowerDNS database connection Default: postgres
*/
	Adapter interface{} `yaml:"adapter,omitempty"`

	/*Database - Descr: Database for the PowerDNS database connection Default: bosh
*/
	Database interface{} `yaml:"database,omitempty"`

	/*Password - Descr: Password for the PowerDNS database connection Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Host - Descr: Address for the PowerDNS database Default: 127.0.0.1
*/
	Host interface{} `yaml:"host,omitempty"`

}