package nats 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NatsJob struct {

	/*Nats - Descr: Password clients must use to access nats mbus Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}