package cloud_controller_clock 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AppEvents struct {

	/*CutoffAgeInDays - Descr: How old an app event should stay in cloud controller database before being cleaned up Default: 31
*/
	CutoffAgeInDays interface{} `yaml:"cutoff_age_in_days,omitempty"`

}