package cloud_controller_clock 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BlobstoreDelete struct {

	/*TimeoutInSeconds - Descr: The longest this job can take before it is cancelled Default: <nil>
*/
	TimeoutInSeconds interface{} `yaml:"timeout_in_seconds,omitempty"`

}