package cloud_controller_clock 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nats struct {

	/*Port - Descr: IP port of Cloud Foundry NATS server Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Machines - Descr: IP of each NATS cluster member. Default: <nil>
*/
	Machines interface{} `yaml:"machines,omitempty"`

	/*User - Descr: Username for cc client to connect to NATS Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Password - Descr: Password for cc client to connect to NATS Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}