package cloud_controller_clock 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PendingPackages struct {

	/*FrequencyInSeconds - Descr: How often the package pending cleanup job runs Default: 300
*/
	FrequencyInSeconds interface{} `yaml:"frequency_in_seconds,omitempty"`

	/*ExpirationInSeconds - Descr: How long packages can remain in pending state before being cleaned up Default: 1200
*/
	ExpirationInSeconds interface{} `yaml:"expiration_in_seconds,omitempty"`

}