package cloud_controller_clock 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Thresholds struct {

	/*Api - Descr: The cc will restart if memory remains above this threshold for 3 monit cycles Default: 3750
*/
	Api *Api `yaml:"api,omitempty"`

}