package hm9000 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DeaNext struct {

	/*HeartbeatIntervalInSeconds - Descr: Heartbeat interval for DEAs Default: <nil>
*/
	HeartbeatIntervalInSeconds interface{} `yaml:"heartbeat_interval_in_seconds,omitempty"`

}