package hm9000 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Hm9000 struct {

	/*Cc - Descr: Password used to access the bulk_api, health_manager uses it to connect to the cc, announced over NATS Default: <nil>
*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*Etcd - Descr: IPs pointing to the ETCD cluster Default: <nil>
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*MetronAgent - Descr: Incoming port for dropsonde log messages Default: 3457
*/
	MetronAgent *MetronAgent `yaml:"metron_agent,omitempty"`

	/*Nats - Descr:  Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*DeaNext - Descr: Heartbeat interval for DEAs Default: <nil>
*/
	DeaNext *DeaNext `yaml:"dea_next,omitempty"`

	/*FetcherNetworkTimeoutInSeconds - Descr: Each API call to the CC must succeed within this timeout. Default: 30
*/
	FetcherNetworkTimeoutInSeconds interface{} `yaml:"fetcher_network_timeout_in_seconds,omitempty"`

	/*Port - Descr: The port to serve API requests Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Domain - Descr: domain where cloud_controller will listen (api.domain) often the same as the system domain Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*DesiredStateBatchSize - Descr: The batch size when fetching desired state information from the CC. Default: 5000
*/
	DesiredStateBatchSize interface{} `yaml:"desired_state_batch_size,omitempty"`

	/*ServerCert - Descr: PEM-encoded server certificate Default: <nil>
*/
	ServerCert interface{} `yaml:"server_cert,omitempty"`

	/*CaCert - Descr: PEM-encoded CA certificate Default: <nil>
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

	/*Hm9000 - Descr: PEM-encoded CA certificate Default: <nil>
*/
	Hm9000 *Hm9000 `yaml:"hm9000,omitempty"`

	/*ServerKey - Descr: PEM-encoded server key Default: <nil>
*/
	ServerKey interface{} `yaml:"server_key,omitempty"`

	/*SenderMessageLimit - Descr: The maximum number of messages the sender should send per invocation. Default: 60
*/
	SenderMessageLimit interface{} `yaml:"sender_message_limit,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}