package postgres 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PostgresJob struct {

	/*Databases - Descr: A map of additional key/value pairs to include as extra configuration properties Default: <nil>
*/
	Databases *Databases `yaml:"databases,omitempty"`

}