package vm_consul 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Consul struct {

	/*Service - Descr: Name for advertising/discovering this service over consul Default: vm-node
*/
	Service *Service `yaml:"service,omitempty"`

}