package vm_consul 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Service struct {

	/*Name - Descr: Name for advertising/discovering this service over consul Default: vm-node
*/
	Name interface{} `yaml:"name,omitempty"`

}