package vm_consul 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VmConsulJob struct {

	/*Consul - Descr: Name for advertising/discovering this service over consul Default: vm-node
*/
	Consul *Consul `yaml:"consul,omitempty"`

}