package converger 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConvergerJob struct {

	/*Diego - Descr: capacity of the tls client cache Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}