package converger 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Converger - Descr: address at which to serve debug info Default: 0.0.0.0:17002
*/
	Converger *Converger `yaml:"converger,omitempty"`

}