package consul_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConsulAgent struct {

	/*Consul - Descr: Map of consul service definitions. Default: map[]
*/
	Consul *Consul `yaml:"consul,omitempty"`

}