package vsphere_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AgentBlobstore struct {

	/*SecretAccessKey - Descr: AWS secret_access_key for agent used by s3 blobstore plugin Default: <nil>
*/
	SecretAccessKey interface{} `yaml:"secret_access_key,omitempty"`

	/*UseSsl - Descr: Whether the agent blobstore plugin should use SSL to connect to the blobstore server Default: <nil>
*/
	UseSsl interface{} `yaml:"use_ssl,omitempty"`

	/*S3Region - Descr: AWS region used by s3 blobstore plugin Default: <nil>
*/
	S3Region interface{} `yaml:"s3_region,omitempty"`

	/*SslVerifyPeer - Descr: Whether the agent blobstore plugin should verify its peer when using SSL Default: <nil>
*/
	SslVerifyPeer interface{} `yaml:"ssl_verify_peer,omitempty"`

	/*AccessKeyId - Descr: AWS access_key_id for agent used by s3 blobstore plugin Default: <nil>
*/
	AccessKeyId interface{} `yaml:"access_key_id,omitempty"`

	/*Address - Descr: Address for agent to connect to blobstore server used by simple blobstore plugin Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*S3ForcePathStyle - Descr: Whether the agent blobstore plugin will always use path style for bucket access Default: <nil>
*/
	S3ForcePathStyle interface{} `yaml:"s3_force_path_style,omitempty"`

	/*Host - Descr: Host of agent blobstore server used by simple blobstore plugin Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*S3Port - Descr: Port of agent blobstore server used by s3 blobstore plugin Default: <nil>
*/
	S3Port interface{} `yaml:"s3_port,omitempty"`

	/*S3SignatureVersion - Descr: Signature version used to connect to an s3 blobstore Default: <nil>
*/
	S3SignatureVersion interface{} `yaml:"s3_signature_version,omitempty"`

	/*S3MultipartThreshold - Descr: Agent blobstore threshold for multipart uploads Default: <nil>
*/
	S3MultipartThreshold interface{} `yaml:"s3_multipart_threshold,omitempty"`

}