package vsphere_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VsphereCpiJob struct {

	/*Agent - Descr: Whether the agent blobstore plugin will always use path style for bucket access Default: <nil>
*/
	Agent *Agent `yaml:"agent,omitempty"`

	/*Blobstore - Descr: Host of blobstore server used by simple blobstore plugin Default: <nil>
*/
	Blobstore *Blobstore `yaml:"blobstore,omitempty"`

	/*Nats - Descr: Address of the nats server Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Vcenter - Descr: Address of vCenter server used by vsphere cpi Default: <nil>
*/
	Vcenter *Vcenter `yaml:"vcenter,omitempty"`

	/*Env - Descr: Http proxy to connect to cloud API's Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Ntp - Descr: List of ntp server IPs. pool.ntp.org attempts to return IPs closest to your location, but you can still specify if needed. Default: [0.pool.ntp.org 1.pool.ntp.org]
*/
	Ntp interface{} `yaml:"ntp,omitempty"`

}