package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cc struct {

	/*SrvApiUri - Descr: API URI of cloud controller Default: <nil>
*/
	SrvApiUri interface{} `yaml:"srv_api_uri,omitempty"`

}