package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ClientsDoppler struct {

	/*Secret - Descr: Doppler's client secret to connect to UAA Default: <nil>
*/
	Secret interface{} `yaml:"secret,omitempty"`

}