package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Clients struct {

	/*Doppler - Descr: Doppler's client secret to connect to UAA Default: <nil>
*/
	Doppler *ClientsDoppler `yaml:"doppler,omitempty"`

}