package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Doppler struct {

	/*UaaClientId - Descr: Doppler's client id to connect to UAA Default: doppler
*/
	UaaClientId interface{} `yaml:"uaa_client_id,omitempty"`

	/*Secret - Descr: Doppler's client secret to connect to UAA Default: <nil>
*/
	Secret interface{} `yaml:"secret,omitempty"`

}