package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Login struct {

	/*Protocol - Descr: Protocol to use to connect to UAA (used in case uaa.url is not set) Default: https
*/
	Protocol interface{} `yaml:"protocol,omitempty"`

}