package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Uaa struct {

	/*Url - Descr: URL of UAA Default: <nil>
*/
	Url interface{} `yaml:"url,omitempty"`

	/*Clients - Descr: Doppler's client secret to connect to UAA Default: <nil>
*/
	Clients *Clients `yaml:"clients,omitempty"`

}