package openstack_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Openstack struct {

	/*WaitResourcePollInterval - Descr: Changes the delay (in seconds) between each status check to OpenStack when creating a resource (optional, by default 5) Default: 5
*/
	WaitResourcePollInterval interface{} `yaml:"wait_resource_poll_interval,omitempty"`

	/*ApiKey - Descr: OpenStack API key (required) Default: <nil>
*/
	ApiKey interface{} `yaml:"api_key,omitempty"`

	/*DefaultKeyName - Descr: Default OpenStack keypair to use when spinning up new VMs (required) Default: <nil>
*/
	DefaultKeyName interface{} `yaml:"default_key_name,omitempty"`

	/*Project - Descr: OpenStack project name (required for Keystone API V3) Default: <nil>
*/
	Project interface{} `yaml:"project,omitempty"`

	/*EndpointType - Descr: OpenStack endpoint type Default: publicURL
*/
	EndpointType interface{} `yaml:"endpoint_type,omitempty"`

	/*BootFromVolume - Descr: Boot from volume Default: false
*/
	BootFromVolume interface{} `yaml:"boot_from_volume,omitempty"`

	/*AuthUrl - Descr: URL of the OpenStack Identity endpoint to connect to (required) Default: <nil>
*/
	AuthUrl interface{} `yaml:"auth_url,omitempty"`

	/*DefaultSecurityGroups - Descr: Default OpenStack security groups to use when spinning up new VMs (required) Default: <nil>
*/
	DefaultSecurityGroups interface{} `yaml:"default_security_groups,omitempty"`

	/*IgnoreServerAvailabilityZone - Descr: When creating a disk, do not use the availability zone of the server, fall back to Openstacks default Default: false
*/
	IgnoreServerAvailabilityZone interface{} `yaml:"ignore_server_availability_zone,omitempty"`

	/*UseDhcp - Descr: Whether to use DHCP when configuring networking on VM (for both manual and dynamic) Default: true
*/
	UseDhcp interface{} `yaml:"use_dhcp,omitempty"`

	/*Domain - Descr: OpenStack domain (required for Keystone API V3) Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*StemcellPublicVisibility - Descr: Set public visibility for stemcells Default: false
*/
	StemcellPublicVisibility interface{} `yaml:"stemcell_public_visibility,omitempty"`

	/*Tenant - Descr: OpenStack tenant name (required for Keystone API V2) Default: <nil>
*/
	Tenant interface{} `yaml:"tenant,omitempty"`

	/*ConfigDrive - Descr: Config drive device (cdrom or disk) to use as metadata service on OpenStack (optional) Default: <nil>
*/
	ConfigDrive interface{} `yaml:"config_drive,omitempty"`

	/*HumanReadableVmNames - Descr: When creating a VM, use the job name as VM name if true. Otherwise use a generated UUID as name. If this parameter is set to true, the registry.endpoint parameter has to be set. Default: false
*/
	HumanReadableVmNames interface{} `yaml:"human_readable_vm_names,omitempty"`

	/*Username - Descr: OpenStack user name (required) Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Region - Descr: OpenStack region (optional) Default: <nil>
*/
	Region interface{} `yaml:"region,omitempty"`

	/*StateTimeout - Descr: Timeout (in seconds) for OpenStack resources desired state Default: 300
*/
	StateTimeout interface{} `yaml:"state_timeout,omitempty"`

	/*ConnectionOptions - Descr: Hash containing optional connection parameters to the OpenStack API (optional) Default: <nil>
*/
	ConnectionOptions interface{} `yaml:"connection_options,omitempty"`

}