package postgres_9

/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
 */
type Postgres9 struct {

	/*Postgres - Descr: TCP port Postgres listens on Default: 5432
	 */
	Postgres *Postgres `yaml:"postgres,omitempty"`
}
