package metron_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Logrotate struct {

	/*FreqMin - Descr: The frequency in minutes which logrotate will rotate VM logs Default: 5
*/
	FreqMin interface{} `yaml:"freq_min,omitempty"`

	/*Rotate - Descr: The number of files that logrotate will keep around on the VM Default: 7
*/
	Rotate interface{} `yaml:"rotate,omitempty"`

	/*Size - Descr: The size at which logrotate will decide to rotate the log file Default: 50M
*/
	Size interface{} `yaml:"size,omitempty"`

}