package metron_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MetronAgentTls struct {

	/*ClientCert - Descr: TLS client certificate Default: 
*/
	ClientCert interface{} `yaml:"client_cert,omitempty"`

	/*ClientKey - Descr: TLS client key Default: 
*/
	ClientKey interface{} `yaml:"client_key,omitempty"`

}