package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SmokeTestsJob struct {

	/*SmokeTests - Descr: A token used by the tests when creating Apps / Spaces Default: CF_SMOKE_TESTS
*/
	SmokeTests *SmokeTests `yaml:"smoke_tests,omitempty"`

}