package registry 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Aws struct {

	/*SslCaFile - Descr: The path to a CA cert bundle in PEM format Default: <nil>
*/
	SslCaFile interface{} `yaml:"ssl_ca_file,omitempty"`

	/*Region - Descr: AWS EC2 Region Default: <nil>
*/
	Region interface{} `yaml:"region,omitempty"`

	/*MaxRetries - Descr: Max number of retries to connect to AWS Default: 2
*/
	MaxRetries interface{} `yaml:"max_retries,omitempty"`

	/*SslCaPath - Descr: The path the a CA cert directory Default: <nil>
*/
	SslCaPath interface{} `yaml:"ssl_ca_path,omitempty"`

	/*CredentialsSource - Descr: AWS credentials source Default: static
*/
	CredentialsSource interface{} `yaml:"credentials_source,omitempty"`

	/*SslVerifyPeer - Descr: When true the HTTP handler validate server certificates for HTTPS requests Default: <nil>
*/
	SslVerifyPeer interface{} `yaml:"ssl_verify_peer,omitempty"`

	/*Ec2Endpoint - Descr: The service endpoint for Amazon EC2 (optional, if not supplied default region endpoint will be used) Default: <nil>
*/
	Ec2Endpoint interface{} `yaml:"ec2_endpoint,omitempty"`

	/*AccessKeyId - Descr: AWS IAM Access Key ID Default: <nil>
*/
	AccessKeyId interface{} `yaml:"access_key_id,omitempty"`

	/*SecretAccessKey - Descr: AWS IAM Secret Access Key Default: <nil>
*/
	SecretAccessKey interface{} `yaml:"secret_access_key,omitempty"`

	/*ElbEndpoint - Descr: The service endpoint for Amazon Elastic Load Balancing (optional, if not supplied default region endpoint will be used) Default: <nil>
*/
	ElbEndpoint interface{} `yaml:"elb_endpoint,omitempty"`

}