package rootfses 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*RootfsCflinuxfs2 - Descr: certficates to add to the rootfs trust store Default: <nil>
*/
	RootfsCflinuxfs2 *RootfsCflinuxfs2 `yaml:"rootfs_cflinuxfs2,omitempty"`

}