package rootfses 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Rootfses struct {

	/*Diego - Descr: certficates to add to the rootfs trust store Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}