package rootfses 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RootfsCflinuxfs2 struct {

	/*TrustedCerts - Descr: certficates to add to the rootfs trust store Default: <nil>
*/
	TrustedCerts interface{} `yaml:"trusted_certs,omitempty"`

}