package google_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AgentBlobstore struct {

	/*Options - Descr: Options for the blobstore used by deployed BOSH agents Default: map[]
*/
	Options interface{} `yaml:"options,omitempty"`

}