package google_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*Mbus - Descr: Mbus URL used by deployed BOSH agents Default: <nil>
*/
	Mbus interface{} `yaml:"mbus,omitempty"`

	/*Blobstore - Descr: Options for the blobstore used by deployed BOSH agents Default: map[]
*/
	Blobstore *AgentBlobstore `yaml:"blobstore,omitempty"`

}