package google_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Blobstore struct {

	/*Path - Descr: local blobstore path Default: <nil>
*/
	Path interface{} `yaml:"path,omitempty"`

	/*Address - Descr: Address of blobstore server used by simple blobstore plugin Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Port - Descr: Port of blobstore server used by simple blobstore plugin Default: 25250
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Agent - Descr: Password agent uses to connect to blobstore used by simple blobstore plugin Default: <nil>
*/
	Agent *BlobstoreAgent `yaml:"agent,omitempty"`

	/*Provider - Descr: Provider of the blobstore used by director and agent (dav|simple) Default: dav
*/
	Provider interface{} `yaml:"provider,omitempty"`

}