package google_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Client struct {

	/*Tls - Descr: Registry Client Key (PEM format) Default: <nil>
*/
	Tls *Tls `yaml:"tls,omitempty"`

}