package google_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Google struct {

	/*DefaultZone - Descr: Google Compute Engine Default Zone Default: <nil>
*/
	DefaultZone interface{} `yaml:"default_zone,omitempty"`

	/*Project - Descr: Google Compute Engine project Default: <nil>
*/
	Project interface{} `yaml:"project,omitempty"`

	/*JsonKey - Descr: Google Compute Engine JSON key Default: 
*/
	JsonKey interface{} `yaml:"json_key,omitempty"`

	/*DefaultRootDiskSizeGb - Descr: The default size (in Gb) of the instances root disk  Default: 0
*/
	DefaultRootDiskSizeGb interface{} `yaml:"default_root_disk_size_gb,omitempty"`

	/*DefaultRootDiskType - Descr: The name of the default Google Compute Engine Disk Type the CPI will use when creating the instances root disk Default: 
*/
	DefaultRootDiskType interface{} `yaml:"default_root_disk_type,omitempty"`

}