package google_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Registry struct {

	/*Client - Descr: Registry Client Key (PEM format) Default: <nil>
*/
	Client *Client `yaml:"client,omitempty"`

	/*Host - Descr: Registry Hostname Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Protocol - Descr: Registry Protocol (http|https) Default: http
*/
	Protocol interface{} `yaml:"protocol,omitempty"`

	/*Username - Descr: Registry Username Default: admin
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Port - Descr: Registry Port Default: 25777
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Password - Descr: Registry Password Default: admin
*/
	Password interface{} `yaml:"password,omitempty"`

	/*UseGceMetadata - Descr: Google Compute Engine metadata should be used instead of BOSH registry Default: true
*/
	UseGceMetadata interface{} `yaml:"use_gce_metadata,omitempty"`

}