package google_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Tls struct {

	/*InsecureSkipVerify - Descr: Skip Registry server's certificate chain and host name verification Default: true
*/
	InsecureSkipVerify interface{} `yaml:"insecure_skip_verify,omitempty"`

	/*Key - Descr: Registry Client Key (PEM format) Default: <nil>
*/
	Key interface{} `yaml:"key,omitempty"`

	/*Cacert - Descr: Registry Client Root CA certificates (PEM format) Default: <nil>
*/
	Cacert interface{} `yaml:"cacert,omitempty"`

	/*Cert - Descr: Registry Client Certificate (PEM format) Default: <nil>
*/
	Cert interface{} `yaml:"cert,omitempty"`

}