package route_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nats struct {

	/*Password - Descr: Password for NATS authentication Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Machines - Descr: IPs of each NATS cluster member Default: <nil>
*/
	Machines interface{} `yaml:"machines,omitempty"`

	/*Port - Descr: TCP port of NATS servers Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*User - Descr: User name for NATS authentication Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

}