package dedicated_node 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*BackendPort - Descr: The backend port for the redis-agent process to listen on Default: 9876
*/
	BackendPort interface{} `yaml:"backend_port,omitempty"`

}