package dedicated_node 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DedicatedNodeJob struct {

	/*Redis - Descr: Configure interval time in seconds that slaves send PINGs to server. Default: 10
*/
	Redis *Redis `yaml:"redis,omitempty"`

}