package dedicated_node 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Limits struct {

	/*Maxclients - Descr: Set the max number of connected clients at the same time Default: 10000
*/
	Maxclients interface{} `yaml:"maxclients,omitempty"`

}