package dedicated_node 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Security struct {

	/*RequirePass - Descr: Require clients to issue AUTH PASSWORD before processing any other commands. Default: <nil>
*/
	RequirePass interface{} `yaml:"require_pass,omitempty"`

}