package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BrokerDeregistrar struct {

	/*Cf - Descr: Skip SSL validation when connecting to Cloud Foundry API Default: false
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*Broker - Descr: Name of the service broker Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

}