package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Service struct {

	/*Plans - Descr: Array of MySQL plans Default: <nil>
*/
	Plans interface{} `yaml:"plans,omitempty"`

	/*Name - Descr: Name of the MySQL service Default: <nil>
*/
	Name interface{} `yaml:"name,omitempty"`

	/*MaxUserConnectionsDefault - Descr: number of user connections to allow in a plan if not specified Default: 40
*/
	MaxUserConnectionsDefault interface{} `yaml:"max_user_connections_default,omitempty"`

}