package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Standalone struct {

	/*Host - Descr: Hostname of proxy or load balancer used to communicate with MySQL nodes in a standalone deployment Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Username - Descr: MySQL admin username Default: root
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Password - Descr: MySQL admin password Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Port - Descr: Port used to communicate with MySQL nodes Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

}