package cf_mysql_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MysqlNode struct {

	/*PersistentDisk - Descr: Size of the persistent disk allocated to the MySQL node for storage Default: <nil>
*/
	PersistentDisk interface{} `yaml:"persistent_disk,omitempty"`

	/*Host - Descr: Host (DNS) or IP address used by the broker and bound applications to reach the service Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*GcacheSize - Descr: Cache size used by galera (maximum amount of data possible in an IST), in MB Default: 512
*/
	GcacheSize interface{} `yaml:"gcache_size,omitempty"`

	/*AdminUsername - Descr: Username for the admin MySQL account Default: root
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

	/*AdminPassword - Descr: Password for the admin MySQL account Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*IbLogFileSize - Descr: Size of the ib_log_file used by innodb, in MB Default: 1024
*/
	IbLogFileSize interface{} `yaml:"ib_log_file_size,omitempty"`

	/*Port - Descr: Port used by the broker and bound applications to reach the service Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

}