package cloud_controller_worker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Generic struct {

	/*NumberOfWorkers - Descr: Number of generic cloud_controller_worker workers Default: 1
*/
	NumberOfWorkers interface{} `yaml:"number_of_workers,omitempty"`

}