package cloud_controller_worker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Hm9000 struct {

	/*Url - Descr: URL of the hm9000 server Default: <nil>
*/
	Url interface{} `yaml:"url,omitempty"`

}