package cloud_controller_worker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Jwt struct {

	/*VerificationKey - Descr: ssl cert defined in the manifest by the UAA, required by the cc to communicate with UAA Default: 
*/
	VerificationKey interface{} `yaml:"verification_key,omitempty"`

}