package cloud_controller_worker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ServiceUsageEvents struct {

	/*CutoffAgeInDays - Descr: How old a service usage event should stay in cloud controller database before being cleaned up Default: 31
*/
	CutoffAgeInDays interface{} `yaml:"cutoff_age_in_days,omitempty"`

}