package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Claims struct {

	/*Exclude - Descr: List of claims to exclude from the JWT-based OAuth2 tokens Default: <nil>
*/
	Exclude interface{} `yaml:"exclude,omitempty"`

}