package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Logout struct {

	/*Redirect - Descr: When set to false, this allows an operator to leverage an open redirect on the UAA (/logout.do?redirect=google.com). No open redirect enabled Default: true
*/
	Redirect *Redirect `yaml:"redirect,omitempty"`

}