package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Notifications struct {

	/*Url - Descr: The url for the notifications service (configure to use Notifications Service instead of SMTP server) Default: <nil>
*/
	Url interface{} `yaml:"url,omitempty"`

}