package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Redirect struct {

	/*Url - Descr: The Location of the redirect header following a logout of the the UAA (/logout.do). Default: /login
*/
	Url interface{} `yaml:"url,omitempty"`

	/*Parameter - Descr: When set to false, this allows an operator to leverage an open redirect on the UAA (/logout.do?redirect=google.com). No open redirect enabled Default: true
*/
	Parameter *Parameter `yaml:"parameter,omitempty"`

}