package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Socket struct {

	/*ConnectionManagerTimeout - Descr: Timeout in milliseconds for connection pooling for SAML metadata HTTP requests Default: 10000
*/
	ConnectionManagerTimeout interface{} `yaml:"connectionManagerTimeout,omitempty"`

	/*SoTimeout - Descr: Read timeout in milliseconds for SAML metadata HTTP requests Default: 10000
*/
	SoTimeout interface{} `yaml:"soTimeout,omitempty"`

}