package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaJob struct {

	/*Domain - Descr: Deprecated. Use uaa.url for setting the location of UAA Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*Uaa - Descr: Number of months after which current password expires Default: 0
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Uaadb - Descr: The list of database Roles used in UAA database including tag/name/password Default: <nil>
*/
	Uaadb *Uaadb `yaml:"uaadb,omitempty"`

	/*Env - Descr: Set No_Proxy across the VMs Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Login - Descr: Deprecated. Use login.saml.providers list objects Default: 1
*/
	Login *Login `yaml:"login,omitempty"`

}