package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaLogin struct {

	/*ClientSecret - Descr: Default login client secret, if no login client is defined Default: <nil>
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

}