package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Username struct {

	/*Text - Descr: The text used to prompt for a username during login Default: Email
*/
	Text interface{} `yaml:"text,omitempty"`

}