package uaa_postgres 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Postgres struct {

	/*Port - Descr: The database port Default: 5524
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Address - Descr: The database address Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Databases - Descr: A list of databases and associated properties to create Default: <nil>
*/
	Databases interface{} `yaml:"databases,omitempty"`

	/*Roles - Descr: A list of database roles and associated properties to create Default: <nil>
*/
	Roles interface{} `yaml:"roles,omitempty"`

	/*MaxConnections - Descr: Maximum number of database connections Default: 500
*/
	MaxConnections interface{} `yaml:"max_connections,omitempty"`

	/*LogLinePrefix - Descr: The postgres `printf` style string that is output at the beginning of each log line Default: %m: 
*/
	LogLinePrefix interface{} `yaml:"log_line_prefix,omitempty"`

}