package uaa_postgres 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaPostgresJob struct {

	/*Postgres - Descr: The postgres `printf` style string that is output at the beginning of each log line Default: %m: 
*/
	Postgres *Postgres `yaml:"postgres,omitempty"`

}