package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CompiledPackageCache struct {

	/*Options - Descr: Whether s3 blobstore plugin will always use path style for bucket access Default: false
*/
	Options *Options `yaml:"options,omitempty"`

	/*Provider - Descr: Provider of the blobstore used for the compiled package cache Default: s3
*/
	Provider interface{} `yaml:"provider,omitempty"`

}