package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Auctioneer struct {

	/*ApiUrl - Descr: Address of the auctioneer API Default: http://auctioneer.service.cf.internal:9016
*/
	ApiUrl interface{} `yaml:"api_url,omitempty"`

}