package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Bbs - Descr: Address of the auctioneer API Default: http://auctioneer.service.cf.internal:9016
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

}