package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Bbs - Descr: PEM-encoded client key Default: <nil>
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

}