package cc_uploader 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CcUploaderJob struct {

	/*Diego - Descr: the interval between job polling requests Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}