package cc_uploader 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*CcUploader - Descr: the interval between job polling requests Default: <nil>
*/
	CcUploader *CcUploader `yaml:"cc_uploader,omitempty"`

}