package ssh_proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cc struct {

	/*ExternalPort - Descr: External port of the Cloud Controller API Default: 9022
*/
	ExternalPort interface{} `yaml:"external_port,omitempty"`

	/*InternalServiceHostname - Descr: Internal service hostname of Cloud Controller Api Default: cloud-controller-ng.service.cf.internal
*/
	InternalServiceHostname interface{} `yaml:"internal_service_hostname,omitempty"`

}