package ssh_proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SshProxy struct {

	/*DebugAddr - Descr: address at which to serve debug info Default: 0.0.0.0:17016
*/
	DebugAddr interface{} `yaml:"debug_addr,omitempty"`

	/*HostKey - Descr: PEM encoded RSA private key used to identify host Default: <nil>
*/
	HostKey interface{} `yaml:"host_key,omitempty"`

	/*EnableDiegoAuth - Descr: Allow ssh access for diego applications Default: false
*/
	EnableDiegoAuth interface{} `yaml:"enable_diego_auth,omitempty"`

	/*UaaSecret - Descr: The oauth client secret used to authenticate the ssh-proxy with the uaa Default: <nil>
*/
	UaaSecret interface{} `yaml:"uaa_secret,omitempty"`

	/*AllowedCiphers - Descr: Comma separated list of allowed cipher algorithms Default: <nil>
*/
	AllowedCiphers interface{} `yaml:"allowed_ciphers,omitempty"`

	/*UaaTokenUrl - Descr: URL of the UAA token endpoint Default: <nil>
*/
	UaaTokenUrl interface{} `yaml:"uaa_token_url,omitempty"`

	/*ListenAddr - Descr: address for the proxy to listen on Default: 0.0.0.0:2222
*/
	ListenAddr interface{} `yaml:"listen_addr,omitempty"`

	/*LogLevel - Descr: Log level Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

	/*Diego - Descr: address at which to serve debug info Default: 0.0.0.0:17016
*/
	Diego *Diego `yaml:"diego,omitempty"`

	/*AllowedMacs - Descr: Comma separated list of allowed MAC algorithms Default: <nil>
*/
	AllowedMacs interface{} `yaml:"allowed_macs,omitempty"`

	/*AllowedKeyexchanges - Descr: Comma separated list of allowed key exchange algorithms Default: <nil>
*/
	AllowedKeyexchanges interface{} `yaml:"allowed_keyexchanges,omitempty"`

	/*DropsondePort - Descr: local metron agent's port Default: 3457
*/
	DropsondePort interface{} `yaml:"dropsonde_port,omitempty"`

	/*Cc - Descr: External port of the Cloud Controller API Default: 9022
*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*Bbs - Descr: Address to the BBS Server Default: bbs.service.cf.internal:8889
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

	/*DiegoCredentials - Descr: Diego Credentials to be used with the Diego authenitcation method Default: <nil>
*/
	DiegoCredentials interface{} `yaml:"diego_credentials,omitempty"`

	/*EnableCfAuth - Descr: Allow ssh access for cf applications Default: false
*/
	EnableCfAuth interface{} `yaml:"enable_cf_auth,omitempty"`

}