package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Director struct {

	/*Port - Descr: Port of the Bosh Director to connect to Default: 25555
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Address - Descr: Address of the Bosh Director to connect to Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

}