package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Graphite struct {

	/*Address - Descr: Graphite address Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Prefix - Descr: Prefix that will be added to all metrics sent to Graphite Default: <nil>
*/
	Prefix interface{} `yaml:"prefix,omitempty"`

	/*Port - Descr: Graphite port Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

}