package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type HealthMonitor struct {

	/*Hm - Descr: Interval (in seconds) to deliver alerts by email (optional) Default: <nil>
*/
	Hm *Hm `yaml:"hm,omitempty"`

	/*Aws - Descr: AWS secret access key Default: <nil>
*/
	Aws *Aws `yaml:"aws,omitempty"`

	/*Nats - Descr: User for the NATS message bus connection Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Env - Descr: HTTPS proxy that the health monitor should use Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*EventNats - Descr: Port of the event NATS message bus port to connect to Default: <nil>
*/
	EventNats *EventNats `yaml:"event_nats,omitempty"`

	/*Director - Descr: Address of the Bosh Director to connect to Default: <nil>
*/
	Director *Director `yaml:"director,omitempty"`

	/*EventNatsEnabled - Descr: Enable event NATS message bus plugin Default: false
*/
	EventNatsEnabled interface{} `yaml:"event_nats_enabled,omitempty"`

}