package garden 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Garden struct {

	/*DefaultContainerRootfs - Descr: path to the rootfs to use when a container specifies no rootfs Default: /var/vcap/packages/busybox
*/
	DefaultContainerRootfs interface{} `yaml:"default_container_rootfs,omitempty"`

	/*ListenAddress - Descr: Garden server listening address. Default: /var/vcap/data/garden/garden.sock
*/
	ListenAddress interface{} `yaml:"listen_address,omitempty"`

	/*DockerRegistryEndpoint - Descr: URL pointing to the Docker registry to use to fetch Docker images. If unset, this will default to the Docker default. Default: <nil>
*/
	DockerRegistryEndpoint interface{} `yaml:"docker_registry_endpoint,omitempty"`

	/*DebugListenAddress - Descr: tcp address on which to serve debug info Default: 0.0.0.0:17013
*/
	DebugListenAddress interface{} `yaml:"debug_listen_address,omitempty"`

	/*InsecureDockerRegistryList - Descr: list of IP:PORT tuples and CIDR subnet masks. Pulling from docker registries with self signed certificates will not be permitted if the registry's address is not listed here. Default: []
*/
	InsecureDockerRegistryList interface{} `yaml:"insecure_docker_registry_list,omitempty"`

	/*Tag - Descr: a string that is a server-wide identifier used for 'global' configuration Default: <nil>
*/
	Tag interface{} `yaml:"tag,omitempty"`

	/*ListenNetwork - Descr: Garden server connection mode (tcp or unix). Default: unix
*/
	ListenNetwork interface{} `yaml:"listen_network,omitempty"`

	/*AllowNetworks - Descr: List of CIDR blocks to which containers will be allowed access (applied after deny). Default: []
*/
	AllowNetworks interface{} `yaml:"allow_networks,omitempty"`

	/*PortPool - Descr: An integer port number used to denote where ports should start being allocated for Net In calls. Uses the Garden default if not set. Default: <nil>
*/
	PortPool *PortPool `yaml:"port_pool,omitempty"`

	/*AllowHostAccess - Descr: A boolean stating whether or not containers started on this host should be able to reach this host. Default: false
*/
	AllowHostAccess interface{} `yaml:"allow_host_access,omitempty"`

	/*NetworkPool - Descr: A CIDR subnet mask specifying the range of subnets available to be assigned to containers. Default: 10.254.0.0/22
*/
	NetworkPool interface{} `yaml:"network_pool,omitempty"`

	/*GraphCleanupThresholdInMb - Descr: Total size of all filesystem layers downloaded from Docker registries before graph cleanup is activated. -1 disables graph cleanup. Default: -1
*/
	GraphCleanupThresholdInMb interface{} `yaml:"graph_cleanup_threshold_in_mb,omitempty"`

	/*NoProxy - Descr: list of comma-separated hosts for which the http and https proxies will be skipped Default: <nil>
*/
	NoProxy interface{} `yaml:"no_proxy,omitempty"`

	/*DefaultContainerGraceTime - Descr: duration after which to reap idle containers Default: 5m
*/
	DefaultContainerGraceTime interface{} `yaml:"default_container_grace_time,omitempty"`

	/*PersistentImageList - Descr: List of Rootfs Paths (directories or docker URLs) which will never be deleted during graph cleanup Default: []
*/
	PersistentImageList interface{} `yaml:"persistent_image_list,omitempty"`

	/*HttpsProxy - Descr: https proxy that the Garden server process will use Default: <nil>
*/
	HttpsProxy interface{} `yaml:"https_proxy,omitempty"`

	/*NetworkMtu - Descr: Maximum network transmission unit length in bytes. Default: 1500
*/
	NetworkMtu interface{} `yaml:"network_mtu,omitempty"`

	/*DenyNetworks - Descr: List of CIDR blocks to which containers will be denied access. Default: []
*/
	DenyNetworks interface{} `yaml:"deny_networks,omitempty"`

	/*Dropsonde - Descr: a URL that points at the Metron agent to which metrics are forwarded. By default, it matches with the default of Metron. Default: <nil>
*/
	Dropsonde *Dropsonde `yaml:"dropsonde,omitempty"`

	/*DnsServers - Descr: Override DNS servers to be used in containers; defaults to the same as the host Default: []
*/
	DnsServers interface{} `yaml:"dns_servers,omitempty"`

	/*MaxContainers - Descr: Maximum number of containers that garden will have running at the same time. It is not recommended to set this larger than 250. Default: 250
*/
	MaxContainers interface{} `yaml:"max_containers,omitempty"`

	/*DestroyContainersOnStart - Descr: destroy existing containers when the server starts up Default: false
*/
	DestroyContainersOnStart interface{} `yaml:"destroy_containers_on_start,omitempty"`

	/*LogLevel - Descr: log level for the Garden server - can be debug, info, error or fatal Default: <nil>
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

	/*Garden - Descr: List of CIDR blocks to which containers will be allowed access (applied after deny). Default: []
*/
	Garden *Garden `yaml:"garden,omitempty"`

	/*HttpProxy - Descr: http proxy that the Garden server process will use Default: <nil>
*/
	HttpProxy interface{} `yaml:"http_proxy,omitempty"`

}