package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cc struct {

	/*BulkApiPassword - Descr: password for the bulk api Default: <nil>
*/
	BulkApiPassword interface{} `yaml:"bulk_api_password,omitempty"`

	/*SrvApiUri - Descr: API URI of cloud controller Default: <nil>
*/
	SrvApiUri interface{} `yaml:"srv_api_uri,omitempty"`

}