package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Loggregator struct {

	/*Etcd - Descr: Number of concurrent requests to ETCD Default: 10
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

}