package collector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Datadog struct {

	/*ApiKey - Descr: Datadog API key Default: <nil>
*/
	ApiKey interface{} `yaml:"api_key,omitempty"`

	/*ApplicationKey - Descr: Datadog application key Default: <nil>
*/
	ApplicationKey interface{} `yaml:"application_key,omitempty"`

}