package collector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Graphite struct {

	/*Address - Descr: IP address of Graphite Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Port - Descr: TCP port of Graphite Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

}