package collector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Opentsdb struct {

	/*Port - Descr: TCP port of OpenTsdb Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Address - Descr: IP address of OpenTsdb Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

}