package tps 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Watcher struct {

	/*DebugAddr - Descr: address at which to serve debug info Default: 0.0.0.0:17015
*/
	DebugAddr interface{} `yaml:"debug_addr,omitempty"`

}