package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Stager - Descr: Address of the Docker Registry used for image caching Default: docker-registry.service.cf.internal:8080
*/
	Stager *Stager `yaml:"stager,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}