package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*Stager - Descr: URL of cc uploader Default: http://cc-uploader.service.cf.internal:9090
*/
	Stager *Stager `yaml:"stager,omitempty"`

}