package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BootstrapEndpoint struct {

	/*Username - Descr: Username used by the bootstrap endpoints for Basic Auth Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Password - Descr: Password used by the bootstrap endpoints for Basic Auth Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}