package broker_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RedisBroker struct {

	/*ServiceName - Descr: Service name Default: p-redis
*/
	ServiceName interface{} `yaml:"service_name,omitempty"`

	/*EnableServiceAccess - Descr: Enable service access to all Default: true
*/
	EnableServiceAccess interface{} `yaml:"enable_service_access,omitempty"`

}