package broker_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Redis struct {

	/*Broker - Descr: Service name Default: p-redis
*/
	Broker *RedisBroker `yaml:"broker,omitempty"`

}