package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Env struct {

	/*NoProxy - Descr: List of comma-separated hosts that should skip connecting to the proxy in the health monitor Default: <nil>
*/
	NoProxy interface{} `yaml:"no_proxy,omitempty"`

	/*HttpProxy - Descr: HTTP proxy that the health monitor should use Default: <nil>
*/
	HttpProxy interface{} `yaml:"http_proxy,omitempty"`

	/*HttpsProxy - Descr: HTTPS proxy that the health monitor should use Default: <nil>
*/
	HttpsProxy interface{} `yaml:"https_proxy,omitempty"`

}