package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Hm struct {

	/*CloudWatchEnabled - Descr: Enable AWS CloudWatch Plugin Default: false
*/
	CloudWatchEnabled interface{} `yaml:"cloud_watch_enabled,omitempty"`

	/*Resurrector - Descr: Time (in seconds) for which an alert in the resurrector is considered 'current'; alerts older than this are ignored when deciding to recreate a job. Default: 600
*/
	Resurrector *Resurrector `yaml:"resurrector,omitempty"`

	/*Tsdb - Descr: Port of TSDB to connect to Default: <nil>
*/
	Tsdb *Tsdb `yaml:"tsdb,omitempty"`

	/*EmThreadpoolSize - Descr: EM thread pool size Default: 20
*/
	EmThreadpoolSize interface{} `yaml:"em_threadpool_size,omitempty"`

	/*EmailRecipients - Descr: Email of recipients (Array) Default: <nil>
*/
	EmailRecipients interface{} `yaml:"email_recipients,omitempty"`

	/*Loglevel - Descr: Level of log messages (fatal, error, warn, info, debug) Default: info
*/
	Loglevel interface{} `yaml:"loglevel,omitempty"`

	/*DatadogEnabled - Descr: Enable DataDog plugin Default: false
*/
	DatadogEnabled interface{} `yaml:"datadog_enabled,omitempty"`

	/*GraphiteEnabled - Descr: Enable Graphite plugin Default: false
*/
	GraphiteEnabled interface{} `yaml:"graphite_enabled,omitempty"`

	/*Http - Descr: TCP port Health Monitor daemon listens on Default: 25923
*/
	Http *Http `yaml:"http,omitempty"`

	/*ResurrectorEnabled - Descr: Enable VM resurrector plugin Default: false
*/
	ResurrectorEnabled interface{} `yaml:"resurrector_enabled,omitempty"`

	/*Datadog - Descr: API Key for DataDog Default: <nil>
*/
	Datadog *Datadog `yaml:"datadog,omitempty"`

	/*SyslogEventForwarderEnabled - Descr: Enable syslog forwarder plugin Default: false
*/
	SyslogEventForwarderEnabled interface{} `yaml:"syslog_event_forwarder_enabled,omitempty"`

	/*TsdbEnabled - Descr: Enable TSDB plugin Default: false
*/
	TsdbEnabled interface{} `yaml:"tsdb_enabled,omitempty"`

	/*Pagerduty - Descr: HTTP proxy to connect to PagerDuty (optional) Default: <nil>
*/
	Pagerduty *Pagerduty `yaml:"pagerduty,omitempty"`

	/*DirectorAccount - Descr: UAA client secret to access Bosh Director Default: 
*/
	DirectorAccount *DirectorAccount `yaml:"director_account,omitempty"`

	/*Smtp - Descr: Port of the SMTP server to connect to (e.g. 25, 465, or 587) Default: <nil>
*/
	Smtp *Smtp `yaml:"smtp,omitempty"`

	/*PagerdutyEnabled - Descr: Enable PagerDuty plugin Default: false
*/
	PagerdutyEnabled interface{} `yaml:"pagerduty_enabled,omitempty"`

	/*EmailNotifications - Descr: Enable email notifications plugin Default: false
*/
	EmailNotifications interface{} `yaml:"email_notifications,omitempty"`

	/*Graphite - Descr: Graphite port Default: <nil>
*/
	Graphite *Graphite `yaml:"graphite,omitempty"`

	/*ConsulEventForwarder - Descr: A ttl time for ttl checks, if set ttl checks will be used Default: <nil>
*/
	ConsulEventForwarder *ConsulEventForwarder `yaml:"consul_event_forwarder,omitempty"`

	/*SyslogEventForwarder - Descr: Custom rule for syslog event forwarder Default: 
*/
	SyslogEventForwarder *SyslogEventForwarder `yaml:"syslog_event_forwarder,omitempty"`

	/*Intervals - Descr: Interval (in seconds) to analyze the status of agents Default: 60
*/
	Intervals *Intervals `yaml:"intervals,omitempty"`

	/*ConsulEventForwarderEnabled - Descr: Enable Consul Plugin Default: false
*/
	ConsulEventForwarderEnabled interface{} `yaml:"consul_event_forwarder_enabled,omitempty"`

	/*EmailInterval - Descr: Interval (in seconds) to deliver alerts by email (optional) Default: <nil>
*/
	EmailInterval interface{} `yaml:"email_interval,omitempty"`

}