package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Tsdb struct {

	/*Port - Descr: Port of TSDB to connect to Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Address - Descr: Address of TSDB to connect to Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

}