package vault 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Consul struct {

	/*Path - Descr: Path for Consul Default: vault/
*/
	Path interface{} `yaml:"path,omitempty"`

	/*Scheme - Descr: Scheme for Consul Default: <nil>
*/
	Scheme interface{} `yaml:"scheme,omitempty"`

	/*Datacenter - Descr: Datacenter for Consul Default: <nil>
*/
	Datacenter interface{} `yaml:"datacenter,omitempty"`

	/*Token - Descr: Access Token for Consul Default: <nil>
*/
	Token interface{} `yaml:"token,omitempty"`

	/*Address - Descr: Address for Consul Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

}