package vault 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type File struct {

	/*Path - Descr: Path for File backend Default: /var/vcap/store/
*/
	Path interface{} `yaml:"path,omitempty"`

}