package vault 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ha struct {

	/*Domain - Descr: The DNS domain name to advertise in HA configuration.  If unspecified, advertise_addr will not be set. Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*Name - Descr: The DNS hostname to advertise in HA configuration.  The keywords (deployment) and (index) will be replaced by the configured deployment and instance index (i.e. 'prod-vault' and '3') Default: (deployment)-(index)
*/
	Name interface{} `yaml:"name,omitempty"`

}