package vault 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Listener struct {

	/*Tcp - Descr: Contents of the PEM-encoded TLS server private key Default: <nil>
*/
	Tcp *Tcp `yaml:"tcp,omitempty"`

}