package vault 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VaultJob struct {

	/*Vault - Descr: Address for Zookeeper Default: localhost:2181
*/
	Vault *Vault `yaml:"vault,omitempty"`

}