package vault 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Vault struct {

	/*Ha - Descr: The DNS hostname to advertise in HA configuration.  The keywords (deployment) and (index) will be replaced by the configured deployment and instance index (i.e. 'prod-vault' and '3') Default: (deployment)-(index)
*/
	Ha *Ha `yaml:"ha,omitempty"`

	/*DisableMlock - Descr: Disable mlock if you're crazy Default: false
*/
	DisableMlock interface{} `yaml:"disable_mlock,omitempty"`

	/*StatsdAddr - Descr: Address for StatsD Default: <nil>
*/
	StatsdAddr interface{} `yaml:"statsd_addr,omitempty"`

	/*Backend - Descr: Address for Zookeeper Default: localhost:2181
*/
	Backend *Backend `yaml:"backend,omitempty"`

	/*Listener - Descr: Contents of the PEM-encoded TLS server private key Default: <nil>
*/
	Listener *Listener `yaml:"listener,omitempty"`

	/*StatsiteAddr - Descr: Address for statsite Default: <nil>
*/
	StatsiteAddr interface{} `yaml:"statsite_addr,omitempty"`

}