package vault 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Zookeeper struct {

	/*Path - Descr: Path for Zookeeper Default: vault/
*/
	Path interface{} `yaml:"path,omitempty"`

	/*Address - Descr: Address for Zookeeper Default: localhost:2181
*/
	Address interface{} `yaml:"address,omitempty"`

}