package vsphere_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConnectionOptions struct {

	/*CaCert - Descr: All required custom CA certificates Default: <nil>
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

}