package broker_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BrokerRegistrar struct {

	/*Broker - Descr: Protocol (http/https) provided to the Cloud Controller when registering/deregistering the broker Default: https
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Cf - Descr: Password of the admin user Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

}