package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AuctioneerJob struct {

	/*Diego - Descr: local metron agent's port Default: 3457
*/
	Diego *Diego `yaml:"diego,omitempty"`

}