package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Auctioneer - Descr: maximum number of idle http connections Default: <nil>
*/
	Auctioneer *Auctioneer `yaml:"auctioneer,omitempty"`

}