package blobstore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*User - Descr: Username agents must use to access blobstore via HTTP Basic Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Password - Descr: Password agents must use to access blobstore via HTTP Basic Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}