package blobstore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BlobstoreJob struct {

	/*Blobstore - Descr: Number of nginx workers for blobstore Default: 2
*/
	Blobstore *Blobstore `yaml:"blobstore,omitempty"`

}