package azure_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*Mbus - Descr: Agent mbus Default: <nil>
*/
	Mbus interface{} `yaml:"mbus,omitempty"`

	/*Blobstore - Descr: AWS secret_access_key for agent used by s3 blobstore plugin Default: <nil>
*/
	Blobstore *AgentBlobstore `yaml:"blobstore,omitempty"`

	/*Nats - Descr: Address of the nats server Default: <nil>
*/
	Nats *AgentNats `yaml:"nats,omitempty"`

}