package file_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type FileServerJob struct {

	/*Diego - Descr: Log level Default: info
*/
	Diego *Diego `yaml:"diego,omitempty"`

}