package postgres_9 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Postgres9Job struct {

	/*Postgres - Descr: Additional Postgres databases to be created (during the startup process) Default: []
*/
	Postgres *Postgres `yaml:"postgres,omitempty"`

}