package aws_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*Blobstore - Descr: Address for agent to connect to blobstore server used by simple blobstore plugin Default: <nil>
*/
	Blobstore *Blobstore `yaml:"blobstore,omitempty"`

	/*Nats - Descr: Address of the nats server Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Mbus - Descr: Agent mbus Default: <nil>
*/
	Mbus interface{} `yaml:"mbus,omitempty"`

	/*Password - Descr: Password agent uses to connect to blobstore used by simple blobstore plugin Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*User - Descr: Username agent uses to connect to blobstore used by simple blobstore plugin Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

}