package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServerJob struct {

	/*EtcdMetricsServer - Descr: basic auth username for metrics server (leave empty for generated) Default: 
*/
	EtcdMetricsServer *EtcdMetricsServer `yaml:"etcd_metrics_server,omitempty"`

}