package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServer struct {

	/*Nats - Descr: NATS server password Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Etcd - Descr: port of ETCD server to instrument Default: 4001
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*EtcdMetricsServer - Descr: port of ETCD server to instrument Default: 4001
*/
	EtcdMetricsServer *EtcdMetricsServer `yaml:"etcd_metrics_server,omitempty"`

	/*Status - Descr: basic auth username for metrics server (leave empty for generated) Default: 
*/
	Status *Status `yaml:"status,omitempty"`

}