package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nats struct {

	/*Port - Descr: NATS server port Default: 4222
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Machines - Descr: array of NATS addresses Default: <nil>
*/
	Machines interface{} `yaml:"machines,omitempty"`

	/*Username - Descr: NATS server username Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Password - Descr: NATS server password Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}