package director 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Local struct {

	/*Users - Descr: List of users that can authenticate with director in non-Uaa mode Default: <nil>
*/
	Users interface{} `yaml:"users,omitempty"`

}