package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*DedicatedNodes - Descr: List of node IPs for the dedicated plan Default: []
*/
	DedicatedNodes interface{} `yaml:"dedicated_nodes,omitempty"`

	/*ServiceName - Descr: Service name displayed in the catalog metadata Default: p-redis
*/
	ServiceName interface{} `yaml:"service_name,omitempty"`

	/*ServiceInstanceLimit - Descr: The maximum number of instances allowed Default: <nil>
*/
	ServiceInstanceLimit interface{} `yaml:"service_instance_limit,omitempty"`

}