package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Redis struct {

	/*Broker - Descr: Service name displayed in the catalog metadata Default: p-redis
*/
	Broker *Broker `yaml:"broker,omitempty"`

}