package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DirectorAccount struct {

	/*Password - Descr: Password to access Bosh Director Default: 
*/
	Password interface{} `yaml:"password,omitempty"`

	/*ClientId - Descr: UAA client id to access Bosh Director Default: 
*/
	ClientId interface{} `yaml:"client_id,omitempty"`

	/*ClientSecret - Descr: UAA client secret to access Bosh Director Default: 
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

	/*CaCert - Descr: Certificate to verify UAA endpoint Default: 
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

	/*User - Descr: User to access Bosh Director Default: 
*/
	User interface{} `yaml:"user,omitempty"`

}