package doppler 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DopplerEndpoint struct {

	/*SharedSecret - Descr: Shared secret used to verify cryptographically signed dropsonde messages Default: <nil>
*/
	SharedSecret interface{} `yaml:"shared_secret,omitempty"`

}