package openstack_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Agent struct {

	/*Blobstore - Descr: Whether the agent blobstore plugin will always use path style for bucket access Default: <nil>
*/
	Blobstore *Blobstore `yaml:"blobstore,omitempty"`

	/*Mbus - Descr: Message bus endpoint for the agent to start accepting agent requests Default: <nil>
*/
	Mbus interface{} `yaml:"mbus,omitempty"`

	/*Password - Descr: Password agent uses to connect to blobstore used by 'simple' blobstore plugin Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*User - Descr: Username agent uses to connect to blobstore used by 'simple' blobstore plugin Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

}