package openstack_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nats struct {

	/*Address - Descr: NATS address used by agent to subscribe to agent requests Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Port - Descr: NATS port used by agent to subscribe to agent requests Default: 4222
*/
	Port interface{} `yaml:"port,omitempty"`

	/*User - Descr: NATS username used by agent to subscribe to agent requests Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Password - Descr: NATS password used by agent to subscribe to agent requests Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}