package aws_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AgentNats struct {

	/*Address - Descr: Address of the nats server Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

}