package aws_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AgentBlobstore struct {

	/*S3SignatureVersion - Descr: Signature version used to connect to an s3 blobstore Default: <nil>
*/
	S3SignatureVersion interface{} `yaml:"s3_signature_version,omitempty"`

	/*SseKmsKeyId - Descr: AWS KMS key ID to use for object encryption. All GET and PUT requests for an object protected by AWS KMS will fail if not made via SSL or using SigV4. Default: <nil>
*/
	SseKmsKeyId interface{} `yaml:"sse_kms_key_id,omitempty"`

	/*S3Region - Descr: AWS region for agent used by s3 blobstore plugin (Required when blobstore.credentials_source is set to `static`) Default: <nil>
*/
	S3Region interface{} `yaml:"s3_region,omitempty"`

	/*AccessKeyId - Descr: AWS access_key_id for agent used by s3 blobstore plugin (Required when blobstore.credentials_source is set to `static`) Default: <nil>
*/
	AccessKeyId interface{} `yaml:"access_key_id,omitempty"`

	/*CredentialsSource - Descr: Where to get AWS credentials for the aws cpi. This can be set to `static` for to use an `access_key_id` and `secret_access_key` or `env_or_profile` to get the credentials from environment variables or an EC2 instance profile. Default: <nil>
*/
	CredentialsSource interface{} `yaml:"credentials_source,omitempty"`

	/*SslVerifyPeer - Descr: Whether the agent blobstore plugin should verify its peer when using SSL Default: <nil>
*/
	SslVerifyPeer interface{} `yaml:"ssl_verify_peer,omitempty"`

	/*S3Port - Descr: Port of agent blobstore server used by s3 blobstore plugin Default: <nil>
*/
	S3Port interface{} `yaml:"s3_port,omitempty"`

	/*Address - Descr: Address for agent to connect to blobstore server used by simple blobstore plugin Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*SecretAccessKey - Descr: AWS secret_access_key for agent used by s3 blobstore plugin (Required when blobstore.credentials_source is set to `static`) Default: <nil>
*/
	SecretAccessKey interface{} `yaml:"secret_access_key,omitempty"`

	/*Host - Descr: Host of agent blobstore server used by simple blobstore plugin Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*ServerSideEncryption - Descr: Server-side encryption algorithm used when storing blobs in S3 (Optional - "AES256"|"aws:kms") Default: <nil>
*/
	ServerSideEncryption interface{} `yaml:"server_side_encryption,omitempty"`

	/*UseSsl - Descr: Whether the agent blobstore plugin should use SSL to connect to the blobstore server Default: <nil>
*/
	UseSsl interface{} `yaml:"use_ssl,omitempty"`

}