package vizzini 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Vizzini struct {

	/*RoutableDomainSuffix - Descr: The deployment's routable domain name Default: <nil>
*/
	RoutableDomainSuffix interface{} `yaml:"routable_domain_suffix,omitempty"`

	/*Verbose - Descr: Run tests in verbose mode Default: false
*/
	Verbose interface{} `yaml:"verbose,omitempty"`

	/*Bbs - Descr: enable ssl for all communication with the bbs Default: true
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

	/*Ssh - Descr: Shared secret for the SSH proxy's Diego authenticator Default: <nil>
*/
	Ssh *Ssh `yaml:"ssh,omitempty"`

	/*EventuallyTimeout - Descr: default timeout for ginkgo assertions Default: <nil>
*/
	EventuallyTimeout interface{} `yaml:"eventually_timeout,omitempty"`

	/*Nodes - Descr: The number of nodes to run the tests with Default: 4
*/
	Nodes interface{} `yaml:"nodes,omitempty"`

}