package vizzini 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VizziniJob struct {

	/*Vizzini - Descr: enable ssl for all communication with the bbs Default: true
*/
	Vizzini *Vizzini `yaml:"vizzini,omitempty"`

}