package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Http struct {

	/*Port - Descr: TCP port Health Monitor daemon listens on Default: 25923
*/
	Port interface{} `yaml:"port,omitempty"`

}