package health_monitor 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SyslogEventForwarder struct {

	/*Port - Descr: Port of the syslog drain Default: 5514
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Address - Descr: IP address of the syslog drain Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Transport - Descr: One of ["udp", "tcp", "relp"] Default: tcp
*/
	Transport interface{} `yaml:"transport,omitempty"`

	/*CustomRule - Descr: Custom rule for syslog event forwarder Default: 
*/
	CustomRule interface{} `yaml:"custom_rule,omitempty"`

}