package canary 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ssl struct {

	/*SkipCertVerify - Descr: Toggles cli verification of the Elastic Runtime API SSL certificate Default: false
*/
	SkipCertVerify interface{} `yaml:"skip_cert_verify,omitempty"`

}